// <auto-generated/>
#pragma warning disable CS0618
using Lyra.Core.EnableBanking.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Lyra.Core.EnableBanking.Aspsps
{
    /// <summary>
    /// Builds and executes requests for operations under \aspsps
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AspspsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AspspsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aspsps{?country*,payment_type*,psu_type*,service*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AspspsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aspsps{?country*,payment_type*,psu_type*,service*}", rawUrl)
        {
        }
        /// <summary>
        /// Get list of ASPSPs with their meta information
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.GetAspspsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 408 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Lyra.Core.EnableBanking.Models.GetAspspsResponse?> GetAsync(Action<RequestConfiguration<global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder.AspspsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Lyra.Core.EnableBanking.Models.GetAspspsResponse> GetAsync(Action<RequestConfiguration<global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder.AspspsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "408", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Lyra.Core.EnableBanking.Models.GetAspspsResponse>(requestInfo, global::Lyra.Core.EnableBanking.Models.GetAspspsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get list of ASPSPs with their meta information
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder.AspspsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder.AspspsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get list of ASPSPs with their meta information
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AspspsRequestBuilderGetQueryParameters 
        {
            /// <summary>Display only ASPSPs from specified country</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("country")]
            public string? Country { get; set; }
#nullable restore
#else
            [QueryParameter("country")]
            public string Country { get; set; }
#endif
            /// <summary>Display only ASPSPs which support specified payment type</summary>
            [Obsolete("This property is deprecated, use PaymentTypeAsPaymentType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("payment_type")]
            public string? PaymentType { get; set; }
#nullable restore
#else
            [QueryParameter("payment_type")]
            public string PaymentType { get; set; }
#endif
            /// <summary>Display only ASPSPs which support specified payment type</summary>
            [QueryParameter("payment_type")]
            public global::Lyra.Core.EnableBanking.Models.PaymentType? PaymentTypeAsPaymentType { get; set; }
            /// <summary>Display only ASPSPs which support specified psu type</summary>
            [Obsolete("This property is deprecated, use PsuTypeAsPSUType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("psu_type")]
            public string? PsuType { get; set; }
#nullable restore
#else
            [QueryParameter("psu_type")]
            public string PsuType { get; set; }
#endif
            /// <summary>Display only ASPSPs which support specified psu type</summary>
            [QueryParameter("psu_type")]
            public global::Lyra.Core.EnableBanking.Models.PSUType? PsuTypeAsPSUType { get; set; }
            /// <summary>Display only ASPSPs which support specified service</summary>
            [Obsolete("This property is deprecated, use ServiceAsService instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("service")]
            public string? Service { get; set; }
#nullable restore
#else
            [QueryParameter("service")]
            public string Service { get; set; }
#endif
            /// <summary>Display only ASPSPs which support specified service</summary>
            [QueryParameter("service")]
            public global::Lyra.Core.EnableBanking.Models.Service? ServiceAsService { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AspspsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder.AspspsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
