// <auto-generated/>
#pragma warning disable CS0618
using Lyra.Core.EnableBanking.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Lyra.Core.EnableBanking.Application
{
    /// <summary>
    /// Builds and executes requests for operations under \application
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplicationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Application.ApplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplicationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/application", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Application.ApplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplicationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/application", rawUrl)
        {
        }
        /// <summary>
        /// Get application associated with provided JWT key ID
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.GetApplicationResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 408 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Lyra.Core.EnableBanking.Models.GetApplicationResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Lyra.Core.EnableBanking.Models.GetApplicationResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "408", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Lyra.Core.EnableBanking.Models.GetApplicationResponse>(requestInfo, global::Lyra.Core.EnableBanking.Models.GetApplicationResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get application associated with provided JWT key ID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Application.ApplicationRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Lyra.Core.EnableBanking.Application.ApplicationRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Lyra.Core.EnableBanking.Application.ApplicationRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApplicationRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
