// <auto-generated/>
#pragma warning disable CS0618
using Lyra.Core.EnableBanking.Accounts;
using Lyra.Core.EnableBanking.Application;
using Lyra.Core.EnableBanking.Aspsps;
using Lyra.Core.EnableBanking.Auth;
using Lyra.Core.EnableBanking.Payments;
using Lyra.Core.EnableBanking.Sessions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Lyra.Core.EnableBanking
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Lyra.Core.EnableBanking.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Lyra.Core.EnableBanking.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The application property</summary>
        public global::Lyra.Core.EnableBanking.Application.ApplicationRequestBuilder Application
        {
            get => new global::Lyra.Core.EnableBanking.Application.ApplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The aspsps property</summary>
        public global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder Aspsps
        {
            get => new global::Lyra.Core.EnableBanking.Aspsps.AspspsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Lyra.Core.EnableBanking.Auth.AuthRequestBuilder Auth
        {
            get => new global::Lyra.Core.EnableBanking.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payments property</summary>
        public global::Lyra.Core.EnableBanking.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::Lyra.Core.EnableBanking.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessions property</summary>
        public global::Lyra.Core.EnableBanking.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Lyra.Core.EnableBanking.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.enablebanking.com";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
