// <auto-generated/>
#pragma warning disable CS0618
using Lyra.Core.EnableBanking.Payments.Item.Transactions.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Lyra.Core.EnableBanking.Payments.Item.Transactions
{
    /// <summary>
    /// Builds and executes requests for operations under \payments\{payment_id}\transactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Lyra.Core.EnableBanking.payments.item.transactions.item collection</summary>
        /// <param name="position">Transaction ID</param>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Payments.Item.Transactions.Item.WithTransaction_ItemRequestBuilder"/></returns>
        public global::Lyra.Core.EnableBanking.Payments.Item.Transactions.Item.WithTransaction_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("transaction_id", position);
                return new global::Lyra.Core.EnableBanking.Payments.Item.Transactions.Item.WithTransaction_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Payments.Item.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/payments/{payment_id}/transactions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Payments.Item.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/payments/{payment_id}/transactions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
