// <auto-generated/>
#pragma warning disable CS0618
using Lyra.Core.EnableBanking.Models;
using Lyra.Core.EnableBanking.Sessions.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Lyra.Core.EnableBanking.Sessions
{
    /// <summary>
    /// Builds and executes requests for operations under \sessions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Lyra.Core.EnableBanking.sessions.item collection</summary>
        /// <param name="position">Previously authorized session ID</param>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Sessions.Item.WithSession_ItemRequestBuilder"/></returns>
        public global::Lyra.Core.EnableBanking.Sessions.Item.WithSession_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("session_id", position);
                return new global::Lyra.Core.EnableBanking.Sessions.Item.WithSession_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Lyra.Core.EnableBanking.sessions.item collection</summary>
        /// <param name="position">Previously authorized session ID</param>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Sessions.Item.WithSession_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Lyra.Core.EnableBanking.Sessions.Item.WithSession_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("session_id", position);
                return new global::Lyra.Core.EnableBanking.Sessions.Item.WithSession_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sessions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sessions", rawUrl)
        {
        }
        /// <summary>
        /// Authorize user session by provided authorization code
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse"/></returns>
        /// <param name="body">Contains data necessary for authorizing session</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 408 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse?> PostAsync(global::Lyra.Core.EnableBanking.Models.AuthorizeSessionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse> PostAsync(global::Lyra.Core.EnableBanking.Models.AuthorizeSessionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "408", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse>(requestInfo, global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Authorize user session by provided authorization code
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Contains data necessary for authorizing session</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Lyra.Core.EnableBanking.Models.AuthorizeSessionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Lyra.Core.EnableBanking.Models.AuthorizeSessionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Sessions.SessionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Lyra.Core.EnableBanking.Sessions.SessionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Lyra.Core.EnableBanking.Sessions.SessionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SessionsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
