// <auto-generated/>
#pragma warning disable CS0618
using Lyra.Core.EnableBanking.Accounts.Item.Balances;
using Lyra.Core.EnableBanking.Accounts.Item.Details;
using Lyra.Core.EnableBanking.Accounts.Item.Transactions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Lyra.Core.EnableBanking.Accounts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts\{account_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAccount_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The balances property</summary>
        public global::Lyra.Core.EnableBanking.Accounts.Item.Balances.BalancesRequestBuilder Balances
        {
            get => new global::Lyra.Core.EnableBanking.Accounts.Item.Balances.BalancesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The details property</summary>
        public global::Lyra.Core.EnableBanking.Accounts.Item.Details.DetailsRequestBuilder Details
        {
            get => new global::Lyra.Core.EnableBanking.Accounts.Item.Details.DetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Accounts.Item.WithAccount_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccount_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Accounts.Item.WithAccount_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccount_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
