// <auto-generated/>
#pragma warning disable CS0618
using Lyra.Core.EnableBanking.Accounts.Item.Transactions.Item;
using Lyra.Core.EnableBanking.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Lyra.Core.EnableBanking.Accounts.Item.Transactions
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts\{account_id}\transactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Lyra.Core.EnableBanking.accounts.item.transactions.item collection</summary>
        /// <param name="position">Transaction ID</param>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.Item.WithTransaction_ItemRequestBuilder"/></returns>
        public global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.Item.WithTransaction_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("transaction_id", position);
                return new global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.Item.WithTransaction_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_id}/transactions{?continuation_key*,date_from*,date_to*,strategy*,transaction_status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_id}/transactions{?continuation_key*,date_from*,date_to*,strategy*,transaction_status*}", rawUrl)
        {
        }
        /// <summary>
        /// Fetching account transactions from ASPSP for an account by its ID
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.HalTransactions"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 408 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Lyra.Core.EnableBanking.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Lyra.Core.EnableBanking.Models.HalTransactions?> GetAsync(Action<RequestConfiguration<global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Lyra.Core.EnableBanking.Models.HalTransactions> GetAsync(Action<RequestConfiguration<global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "408", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Lyra.Core.EnableBanking.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Lyra.Core.EnableBanking.Models.HalTransactions>(requestInfo, global::Lyra.Core.EnableBanking.Models.HalTransactions.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetching account transactions from ASPSP for an account by its ID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetching account transactions from ASPSP for an account by its ID
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TransactionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Key, allowing iterate over multiple API pages of transactions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("continuation_key")]
            public string? ContinuationKey { get; set; }
#nullable restore
#else
            [QueryParameter("continuation_key")]
            public string ContinuationKey { get; set; }
#endif
            /// <summary>Date to fetch transactions from (including the date, UTC timezone is assumed)</summary>
            [QueryParameter("date_from")]
            public Date? DateFrom { get; set; }
            /// <summary>Date to fetch transactions to (including the date, UTC timezone is assumed)</summary>
            [QueryParameter("date_to")]
            public Date? DateTo { get; set; }
            /// <summary>Strategy how transaction are fetched</summary>
            [Obsolete("This property is deprecated, use StrategyAsTransactionsFetchStrategy instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("strategy")]
            public string? Strategy { get; set; }
#nullable restore
#else
            [QueryParameter("strategy")]
            public string Strategy { get; set; }
#endif
            /// <summary>Strategy how transaction are fetched</summary>
            [QueryParameter("strategy")]
            public global::Lyra.Core.EnableBanking.Models.TransactionsFetchStrategy? StrategyAsTransactionsFetchStrategy { get; set; }
            /// <summary>Filter transactions by provided status</summary>
            [Obsolete("This property is deprecated, use TransactionStatusAsTransactionStatus instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("transaction_status")]
            public string? TransactionStatus { get; set; }
#nullable restore
#else
            [QueryParameter("transaction_status")]
            public string TransactionStatus { get; set; }
#endif
            /// <summary>Filter transactions by provided status</summary>
            [QueryParameter("transaction_status")]
            public global::Lyra.Core.EnableBanking.Models.TransactionStatus? TransactionStatusAsTransactionStatus { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TransactionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Lyra.Core.EnableBanking.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
