// <auto-generated/>
#pragma warning disable CS0618
using Lyra.Core.EnableBanking.Accounts.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Lyra.Core.EnableBanking.Accounts
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Lyra.Core.EnableBanking.accounts.item collection</summary>
        /// <param name="position">Account ID</param>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Accounts.Item.WithAccount_ItemRequestBuilder"/></returns>
        public global::Lyra.Core.EnableBanking.Accounts.Item.WithAccount_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("account_id", position);
                return new global::Lyra.Core.EnableBanking.Accounts.Item.WithAccount_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Lyra.Core.EnableBanking.accounts.item collection</summary>
        /// <param name="position">Account ID</param>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Accounts.Item.WithAccount_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Lyra.Core.EnableBanking.Accounts.Item.WithAccount_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("account_id", position);
                return new global::Lyra.Core.EnableBanking.Accounts.Item.WithAccount_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
