// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Scope of access requested from ASPSP and confirmed by PSU
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Access : IAdditionalDataHolder, IParsable
    {
        /// <summary>List of accounts access to which is requested. If not set behaviour depends on thebank: some banks allow users to choose list of accessible accounts through theiraccess consent UI, while other may provide access to all accounts or just access tothe list of accounts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.AccountIdentification>? Accounts { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.AccountIdentification> Accounts { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Request consent with balances access</summary>
        public bool? Balances { get; set; }
        /// <summary>Request consent with transactions access</summary>
        public bool? Transactions { get; set; }
        /// <summary>This parameter specifies the date and time until which the authorised sessionremains valid. The value must be in the RFC3339 date-time format with a timezoneoffset, e.g. `2025-12-01T12:00:00.000000+00:00`. The provided value cannot exceedthe date and time, calculated as &quot;now&quot; + `maximum_consent_validity` (provided inseconds for each ASPSP in response to the GET /aspsps request). The provided valueis subject to adjustment to comply with the ASPSP&apos;s requirements. Specifically, ifthe provided value is less than the minimum consent validity allowed by the ASPSP(e.g., some ASPSPs require a minimum of 1 hour or 1 day), the consent validity willbe adjusted to meet these requirements. However, the session validity will remainexactly as specified. This means that even if the consent remains valid on theASPSP&apos;s side, the session will expire based on the initially provided value.</summary>
        public DateTimeOffset? ValidUntil { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.Access"/> and sets the default values.
        /// </summary>
        public Access()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.Access"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.Access CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.Access();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accounts", n => { Accounts = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.AccountIdentification>(global::Lyra.Core.EnableBanking.Models.AccountIdentification.CreateFromDiscriminatorValue)?.AsList(); } },
                { "balances", n => { Balances = n.GetBoolValue(); } },
                { "transactions", n => { Transactions = n.GetBoolValue(); } },
                { "valid_until", n => { ValidUntil = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.AccountIdentification>("accounts", Accounts);
            writer.WriteBoolValue("balances", Balances);
            writer.WriteBoolValue("transactions", Transactions);
            writer.WriteDateTimeOffsetValue("valid_until", ValidUntil);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
