// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountResource : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Primary account identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AccountIdentification? AccountId { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AccountIdentification AccountId { get; set; }
#endif
        /// <summary>Information about the financial institution servicing the account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification? AccountServicer { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification AccountServicer { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>All account identifiers provided by ASPSPs (including primary identifier available in the accountId field)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.GenericIdentification>? AllAccountIds { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.GenericIdentification> AllAccountIds { get; set; }
#endif
        /// <summary>Specifies the type of the account</summary>
        public global::Lyra.Core.EnableBanking.Models.CashAccountType? CashAccountType { get; set; }
        /// <summary>Specifies the maximum credit or overdraft allowed on the account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AmountType? CreditLimit { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AmountType CreditLimit { get; set; }
#endif
        /// <summary>Specifies the currency of the account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Account description set by PSU or provided by ASPSP</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Details { get; set; }
#nullable restore
#else
        public string Details { get; set; }
#endif
        /// <summary>Primary account identification hash. It can be used for matching accounts between multiple sessions (even in case the sessions are authorized by different PSUs).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdentificationHash { get; set; }
#nullable restore
#else
        public string IdentificationHash { get; set; }
#endif
        /// <summary>List of possible account identification hashes. Identification hash is based on the account number. Some accounts may have multiple account numbers (e.g. IBAN and BBAN). This field contains all possible hashes. Not all of these hashes can be used to uniquely identify an account and that the primary goal of them is to be able to fuzzy matching of accounts by certain properties. Primary hash is included in this list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IdentificationHashes { get; set; }
#nullable restore
#else
        public List<string> IdentificationHashes { get; set; }
#endif
        /// <summary>Specifies whether Enable Banking is confident that the account holder is of legal age or is a minor. The field takes the following values:true if the account holder is of legal age;false if the account holder is a minor;null (or the field is not set) if it is not possible to determine whether the account holder is of legal age or a minor or if the legal age check is not applicable (in cases such as if the account holder is a legal entity or there are multiple account co-holders)</summary>
        public bool? LegalAge { get; set; }
        /// <summary>Account holder(s) name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Postal address of the account holder</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PostalAddress? PostalAddress { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PostalAddress PostalAddress { get; set; }
#endif
        /// <summary>Product Name of the Bank for this account, proprietary definition</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Product { get; set; }
#nullable restore
#else
        public string Product { get; set; }
#endif
        /// <summary>Relationship between the PSU and the account - Account Holder - Co-account Holder - Attorney</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PsuStatus { get; set; }
#nullable restore
#else
        public string PsuStatus { get; set; }
#endif
        /// <summary>Unique account identificator used for fetching account balances and transactions. It is valid only until the session to which the account belongs is in the AUTHORIZED status. It can be not set in case it is know that it is not possible to fetch balances and transactions for the account (for example, in case the account is blocked or closed at the ASPSP side).</summary>
        public Guid? Uid { get; set; }
        /// <summary>Specifies the usage of the account</summary>
        public global::Lyra.Core.EnableBanking.Models.Usage? Usage { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.AccountResource"/> and sets the default values.
        /// </summary>
        public AccountResource()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.AccountResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.AccountResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.AccountResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AccountIdentification>(global::Lyra.Core.EnableBanking.Models.AccountIdentification.CreateFromDiscriminatorValue); } },
                { "account_servicer", n => { AccountServicer = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>(global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification.CreateFromDiscriminatorValue); } },
                { "all_account_ids", n => { AllAccountIds = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.GenericIdentification>(global::Lyra.Core.EnableBanking.Models.GenericIdentification.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cash_account_type", n => { CashAccountType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.CashAccountType>(); } },
                { "credit_limit", n => { CreditLimit = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>(global::Lyra.Core.EnableBanking.Models.AmountType.CreateFromDiscriminatorValue); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "details", n => { Details = n.GetStringValue(); } },
                { "identification_hash", n => { IdentificationHash = n.GetStringValue(); } },
                { "identification_hashes", n => { IdentificationHashes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "legal_age", n => { LegalAge = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "postal_address", n => { PostalAddress = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PostalAddress>(global::Lyra.Core.EnableBanking.Models.PostalAddress.CreateFromDiscriminatorValue); } },
                { "product", n => { Product = n.GetStringValue(); } },
                { "psu_status", n => { PsuStatus = n.GetStringValue(); } },
                { "uid", n => { Uid = n.GetGuidValue(); } },
                { "usage", n => { Usage = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.Usage>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AccountIdentification>("account_id", AccountId);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>("account_servicer", AccountServicer);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.GenericIdentification>("all_account_ids", AllAccountIds);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.CashAccountType>("cash_account_type", CashAccountType);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>("credit_limit", CreditLimit);
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("details", Details);
            writer.WriteStringValue("identification_hash", IdentificationHash);
            writer.WriteCollectionOfPrimitiveValues<string>("identification_hashes", IdentificationHashes);
            writer.WriteBoolValue("legal_age", LegalAge);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PostalAddress>("postal_address", PostalAddress);
            writer.WriteStringValue("product", Product);
            writer.WriteStringValue("psu_status", PsuStatus);
            writer.WriteGuidValue("uid", Uid);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.Usage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
