// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Available address type values</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddressType
    {
        [EnumMember(Value = "Business")]
        #pragma warning disable CS1591
        Business,
        #pragma warning restore CS1591
        [EnumMember(Value = "Correspondence")]
        #pragma warning disable CS1591
        Correspondence,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryTo")]
        #pragma warning disable CS1591
        DeliveryTo,
        #pragma warning restore CS1591
        [EnumMember(Value = "MailTo")]
        #pragma warning disable CS1591
        MailTo,
        #pragma warning restore CS1591
        [EnumMember(Value = "POBox")]
        #pragma warning disable CS1591
        POBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "Postal")]
        #pragma warning disable CS1591
        Postal,
        #pragma warning restore CS1591
        [EnumMember(Value = "Residential")]
        #pragma warning disable CS1591
        Residential,
        #pragma warning restore CS1591
        [EnumMember(Value = "Statement")]
        #pragma warning disable CS1591
        Statement,
        #pragma warning restore CS1591
    }
}
