// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ASPSPData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of available authentication methods. Provided in case multiple methods are available or it is possible to supply authentication credentials while initiating authorization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.AuthMethod>? AuthMethods { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.AuthMethod> AuthMethods { get; set; }
#endif
        /// <summary>Flag showing whether implementation is in beta mode</summary>
        public bool? Beta { get; set; }
        /// <summary>BIC of the ASPSP</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bic { get; set; }
#nullable restore
#else
        public string Bic { get; set; }
#endif
        /// <summary>Two-letter ISO 3166 code of the country, in which ASPSP operates</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>Group, which the ASPSP belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.ASPSPGroup? Group { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.ASPSPGroup Group { get; set; }
#endif
        /// <summary>ASPSP logo URL. It is possible to transform (e.g. resize) the logo by adding special suffixes at the end of the URL. For example, `-/resize/500x/`. For full list of possible transformations, please refer to https://uploadcare.com/docs/transformations/image/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Logo { get; set; }
#nullable restore
#else
        public string Logo { get; set; }
#endif
        /// <summary>Maximum consent validity which bank supports in seconds</summary>
        public int? MaximumConsentValidity { get; set; }
        /// <summary>Name of the ASPSP (i.e. a bank or a similar financial institution)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Supported payment types by country and their properties</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.ResponsePaymentType>? Payments { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.ResponsePaymentType> Payments { get; set; }
#endif
        /// <summary>List of PSU types supported by ASPSP</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.PSUType?>? PsuTypes { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.PSUType?> PsuTypes { get; set; }
#endif
        /// <summary>List of the headers required to indicate to data retrieval endpoints that PSU is online. Either all required PSU headers or none of PSU headers are to be provided, otherwise PSU_HEADER_NOT_PROVIDED error will be returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RequiredPsuHeaders { get; set; }
#nullable restore
#else
        public List<string> RequiredPsuHeaders { get; set; }
#endif
        /// <summary>Applicable only to sandbox environment. Additional information necessary to use sandbox environment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.SandboxInfo? Sandbox { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.SandboxInfo Sandbox { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.ASPSPData"/> and sets the default values.
        /// </summary>
        public ASPSPData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.ASPSPData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.ASPSPData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.ASPSPData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auth_methods", n => { AuthMethods = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.AuthMethod>(global::Lyra.Core.EnableBanking.Models.AuthMethod.CreateFromDiscriminatorValue)?.AsList(); } },
                { "beta", n => { Beta = n.GetBoolValue(); } },
                { "bic", n => { Bic = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "group", n => { Group = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSPGroup>(global::Lyra.Core.EnableBanking.Models.ASPSPGroup.CreateFromDiscriminatorValue); } },
                { "logo", n => { Logo = n.GetStringValue(); } },
                { "maximum_consent_validity", n => { MaximumConsentValidity = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "payments", n => { Payments = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.ResponsePaymentType>(global::Lyra.Core.EnableBanking.Models.ResponsePaymentType.CreateFromDiscriminatorValue)?.AsList(); } },
                { "psu_types", n => { PsuTypes = n.GetCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.PSUType>()?.AsList(); } },
                { "required_psu_headers", n => { RequiredPsuHeaders = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sandbox", n => { Sandbox = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.SandboxInfo>(global::Lyra.Core.EnableBanking.Models.SandboxInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.AuthMethod>("auth_methods", AuthMethods);
            writer.WriteBoolValue("beta", Beta);
            writer.WriteStringValue("bic", Bic);
            writer.WriteStringValue("country", Country);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSPGroup>("group", Group);
            writer.WriteStringValue("logo", Logo);
            writer.WriteIntValue("maximum_consent_validity", MaximumConsentValidity);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.ResponsePaymentType>("payments", Payments);
            writer.WriteCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.PSUType>("psu_types", PsuTypes);
            writer.WriteCollectionOfPrimitiveValues<string>("required_psu_headers", RequiredPsuHeaders);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.SandboxInfo>("sandbox", Sandbox);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
