// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuthMethod : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Authentication approach used in the current authentication method</summary>
        public global::Lyra.Core.EnableBanking.Models.AuthenticationApproach? Approach { get; set; }
        /// <summary>List of credentials which are possible to supply while initiating authorization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.Credential>? Credentials { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.Credential> Credentials { get; set; }
#endif
        /// <summary>Flag showing whether the current authentication method is hidden from the user. If `true` then the user will not be able to select this authentication method. It is only possible to select this authentication method via API.</summary>
        public bool? HiddenMethod { get; set; }
        /// <summary>Internal name of the authentication method</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>PSU type to which the authentication method is applicable</summary>
        public global::Lyra.Core.EnableBanking.Models.PSUType? PsuType { get; set; }
        /// <summary>Human-readable title of the authentication method</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.AuthMethod"/> and sets the default values.
        /// </summary>
        public AuthMethod()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.AuthMethod"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.AuthMethod CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.AuthMethod();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approach", n => { Approach = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.AuthenticationApproach>(); } },
                { "credentials", n => { Credentials = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.Credential>(global::Lyra.Core.EnableBanking.Models.Credential.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hidden_method", n => { HiddenMethod = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "psu_type", n => { PsuType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.AuthenticationApproach>("approach", Approach);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.Credential>("credentials", Credentials);
            writer.WriteBoolValue("hidden_method", HiddenMethod);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>("psu_type", PsuType);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
