// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Authentication approach used in the current authentication method</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuthenticationApproach
    {
        [EnumMember(Value = "REDIRECT")]
        #pragma warning disable CS1591
        REDIRECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECOUPLED")]
        #pragma warning disable CS1591
        DECOUPLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMBEDDED")]
        #pragma warning disable CS1591
        EMBEDDED,
        #pragma warning restore CS1591
    }
}
