// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuthorizeSessionResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Scope of access requested from ASPSP and confirmed by PSU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.Access? Access { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.Access Access { get; set; }
#endif
        /// <summary>List of authorized accounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.AccountResource>? Accounts { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.AccountResource> Accounts { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ASPSP used with the session</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.ASPSP? Aspsp { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.ASPSP Aspsp { get; set; }
#endif
        /// <summary>PSU type used with the session</summary>
        public global::Lyra.Core.EnableBanking.Models.PSUType? PsuType { get; set; }
        /// <summary>ID of the PSU session</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse"/> and sets the default values.
        /// </summary>
        public AuthorizeSessionResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.AuthorizeSessionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access", n => { Access = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.Access>(global::Lyra.Core.EnableBanking.Models.Access.CreateFromDiscriminatorValue); } },
                { "accounts", n => { Accounts = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.AccountResource>(global::Lyra.Core.EnableBanking.Models.AccountResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "aspsp", n => { Aspsp = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSP>(global::Lyra.Core.EnableBanking.Models.ASPSP.CreateFromDiscriminatorValue); } },
                { "psu_type", n => { PsuType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>(); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.Access>("access", Access);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.AccountResource>("accounts", Accounts);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSP>("aspsp", Aspsp);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>("psu_type", PsuType);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
