// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BalanceResource : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Structure aiming to embed the amount and the currency to be used</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AmountType? BalanceAmount { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AmountType BalanceAmount { get; set; }
#endif
        /// <summary>Available balance type values</summary>
        public global::Lyra.Core.EnableBanking.Models.BalanceStatus? BalanceType { get; set; }
        /// <summary>Timestamp of the last change of the balance amount</summary>
        public DateTimeOffset? LastChangeDateTime { get; set; }
        /// <summary>Entry reference of the last transaction contributing to the balance value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastCommittedTransaction { get; set; }
#nullable restore
#else
        public string LastCommittedTransaction { get; set; }
#endif
        /// <summary>Label of the balance</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Reference date for the balance</summary>
        public Date? ReferenceDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.BalanceResource"/> and sets the default values.
        /// </summary>
        public BalanceResource()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.BalanceResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.BalanceResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.BalanceResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "balance_amount", n => { BalanceAmount = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>(global::Lyra.Core.EnableBanking.Models.AmountType.CreateFromDiscriminatorValue); } },
                { "balance_type", n => { BalanceType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.BalanceStatus>(); } },
                { "last_change_date_time", n => { LastChangeDateTime = n.GetDateTimeOffsetValue(); } },
                { "last_committed_transaction", n => { LastCommittedTransaction = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "reference_date", n => { ReferenceDate = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>("balance_amount", BalanceAmount);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.BalanceStatus>("balance_type", BalanceType);
            writer.WriteDateTimeOffsetValue("last_change_date_time", LastChangeDateTime);
            writer.WriteStringValue("last_committed_transaction", LastCommittedTransaction);
            writer.WriteStringValue("name", Name);
            writer.WriteDateValue("reference_date", ReferenceDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
