// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Available balance type values</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BalanceStatus
    {
        [EnumMember(Value = "CLAV")]
        #pragma warning disable CS1591
        CLAV,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLBD")]
        #pragma warning disable CS1591
        CLBD,
        #pragma warning restore CS1591
        [EnumMember(Value = "FWAV")]
        #pragma warning disable CS1591
        FWAV,
        #pragma warning restore CS1591
        [EnumMember(Value = "INFO")]
        #pragma warning disable CS1591
        INFO,
        #pragma warning restore CS1591
        [EnumMember(Value = "ITAV")]
        #pragma warning disable CS1591
        ITAV,
        #pragma warning restore CS1591
        [EnumMember(Value = "ITBD")]
        #pragma warning disable CS1591
        ITBD,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPAV")]
        #pragma warning disable CS1591
        OPAV,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPBD")]
        #pragma warning disable CS1591
        OPBD,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRCD")]
        #pragma warning disable CS1591
        PRCD,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHR")]
        #pragma warning disable CS1591
        OTHR,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALU")]
        #pragma warning disable CS1591
        VALU,
        #pragma warning restore CS1591
        [EnumMember(Value = "XPCD")]
        #pragma warning disable CS1591
        XPCD,
        #pragma warning restore CS1591
    }
}
