// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Specification of a beneficiary
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Beneficiary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identification of the party receiving funds</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification? Creditor { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification Creditor { get; set; }
#endif
        /// <summary>Identification of the account receiving funds</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.GenericIdentification? CreditorAccount { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.GenericIdentification CreditorAccount { get; set; }
#endif
        /// <summary>Identification of the financial institution where the account receiving funds is held</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification? CreditorAgent { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification CreditorAgent { get; set; }
#endif
        /// <summary>ISO 4217 currency code, in which the account receiving funds is held</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreditorCurrency { get; set; }
#nullable restore
#else
        public string CreditorCurrency { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.Beneficiary"/> and sets the default values.
        /// </summary>
        public Beneficiary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.Beneficiary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.Beneficiary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.Beneficiary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creditor", n => { Creditor = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>(global::Lyra.Core.EnableBanking.Models.PartyIdentification.CreateFromDiscriminatorValue); } },
                { "creditor_account", n => { CreditorAccount = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.GenericIdentification>(global::Lyra.Core.EnableBanking.Models.GenericIdentification.CreateFromDiscriminatorValue); } },
                { "creditor_agent", n => { CreditorAgent = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>(global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification.CreateFromDiscriminatorValue); } },
                { "creditor_currency", n => { CreditorCurrency = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>("creditor", Creditor);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.GenericIdentification>("creditor_account", CreditorAccount);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>("creditor_agent", CreditorAgent);
            writer.WriteStringValue("creditor_currency", CreditorCurrency);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
