// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Specifies the type of the account</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CashAccountType
    {
        [EnumMember(Value = "CACC")]
        #pragma warning disable CS1591
        CACC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASH")]
        #pragma warning disable CS1591
        CASH,
        #pragma warning restore CS1591
        [EnumMember(Value = "CARD")]
        #pragma warning disable CS1591
        CARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOAN")]
        #pragma warning disable CS1591
        LOAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "SVGS")]
        #pragma warning disable CS1591
        SVGS,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHR")]
        #pragma warning disable CS1591
        OTHR,
        #pragma warning restore CS1591
    }
}
