// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Specifies the high level purpose of the instruction based on a set of pre-defined categories. This is used by the initiating party to provide information concerning the processing of the payment. It is likely to trigger special processing by any of the agents involved in the payment chain.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CategoryPurposeCode
    {
        [EnumMember(Value = "BONU")]
        #pragma warning disable CS1591
        BONU,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASH")]
        #pragma warning disable CS1591
        CASH,
        #pragma warning restore CS1591
        [EnumMember(Value = "CBLK")]
        #pragma warning disable CS1591
        CBLK,
        #pragma warning restore CS1591
        [EnumMember(Value = "CCRD")]
        #pragma warning disable CS1591
        CCRD,
        #pragma warning restore CS1591
        [EnumMember(Value = "CORT")]
        #pragma warning disable CS1591
        CORT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DCRD")]
        #pragma warning disable CS1591
        DCRD,
        #pragma warning restore CS1591
        [EnumMember(Value = "DIVI")]
        #pragma warning disable CS1591
        DIVI,
        #pragma warning restore CS1591
        [EnumMember(Value = "DVPM")]
        #pragma warning disable CS1591
        DVPM,
        #pragma warning restore CS1591
        [EnumMember(Value = "EPAY")]
        #pragma warning disable CS1591
        EPAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "FCOL")]
        #pragma warning disable CS1591
        FCOL,
        #pragma warning restore CS1591
        [EnumMember(Value = "GOVT")]
        #pragma warning disable CS1591
        GOVT,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEDG")]
        #pragma warning disable CS1591
        HEDG,
        #pragma warning restore CS1591
        [EnumMember(Value = "ICCP")]
        #pragma warning disable CS1591
        ICCP,
        #pragma warning restore CS1591
        [EnumMember(Value = "IDCP")]
        #pragma warning disable CS1591
        IDCP,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTC")]
        #pragma warning disable CS1591
        INTC,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTE")]
        #pragma warning disable CS1591
        INTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOAN")]
        #pragma warning disable CS1591
        LOAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "MP2B")]
        #pragma warning disable CS1591
        MP2B,
        #pragma warning restore CS1591
        [EnumMember(Value = "MP2P")]
        #pragma warning disable CS1591
        MP2P,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHR")]
        #pragma warning disable CS1591
        OTHR,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENS")]
        #pragma warning disable CS1591
        PENS,
        #pragma warning restore CS1591
        [EnumMember(Value = "RPRE")]
        #pragma warning disable CS1591
        RPRE,
        #pragma warning restore CS1591
        [EnumMember(Value = "RRCT")]
        #pragma warning disable CS1591
        RRCT,
        #pragma warning restore CS1591
        [EnumMember(Value = "RVPM")]
        #pragma warning disable CS1591
        RVPM,
        #pragma warning restore CS1591
        [EnumMember(Value = "SALA")]
        #pragma warning disable CS1591
        SALA,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECU")]
        #pragma warning disable CS1591
        SECU,
        #pragma warning restore CS1591
        [EnumMember(Value = "SSBE")]
        #pragma warning disable CS1591
        SSBE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUPP")]
        #pragma warning disable CS1591
        SUPP,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAXS")]
        #pragma warning disable CS1591
        TAXS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAD")]
        #pragma warning disable CS1591
        TRAD,
        #pragma warning restore CS1591
        [EnumMember(Value = "TREA")]
        #pragma warning disable CS1591
        TREA,
        #pragma warning restore CS1591
        [EnumMember(Value = "VATX")]
        #pragma warning disable CS1591
        VATX,
        #pragma warning restore CS1591
        [EnumMember(Value = "WHLD")]
        #pragma warning disable CS1591
        WHLD,
        #pragma warning restore CS1591
    }
}
