// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChargeBearerCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SLEV")]
        #pragma warning disable CS1591
        SLEV,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHAR")]
        #pragma warning disable CS1591
        SHAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEBT")]
        #pragma warning disable CS1591
        DEBT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CRED")]
        #pragma warning disable CS1591
        CRED,
        #pragma warning restore CS1591
    }
}
