// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Contains data necessary for initiating a payment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreatePaymentRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ASPSP that PSU is going to be authenticated to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.ASPSP? Aspsp { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.ASPSP Aspsp { get; set; }
#endif
        /// <summary>Desired authorization method (in case ASPSP integration supports multiple). Supported methods can be obtained from the `auth_methods` field available in ASPSP details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthMethod { get; set; }
#nullable restore
#else
        public string AuthMethod { get; set; }
#endif
        /// <summary>PSU credentials (e.g., user and/or company ID). If not provided through the API, they will be requested from the PSU during authorization. Credentials can be supplied only if `auth_method` is specified; otherwise, a `WRONG_REQUEST_PARAMETERS` error will be returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest_credentials? Credentials { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest_credentials Credentials { get; set; }
#endif
        /// <summary>Preferred PSU language. Two-letter lowercase language code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>Specifies the details required to initiate a payment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PaymentRequestResource? PaymentRequest { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PaymentRequestResource PaymentRequest { get; set; }
#endif
        /// <summary>Specifies the type of payment used</summary>
        public global::Lyra.Core.EnableBanking.Models.PaymentType? PaymentType { get; set; }
        /// <summary>Unique identification of a PSU used by the client application. It can be used to match payments of the same user. Although only hashed value is stored, it is recommended to use anonymised identifiers (i.e. digital ID instead of email or social security number). In case the parameter is not passed by the application, random value will be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PsuId { get; set; }
#nullable restore
#else
        public string PsuId { get; set; }
#endif
        /// <summary>PSU type which consent is created for</summary>
        public global::Lyra.Core.EnableBanking.Models.PSUType? PsuType { get; set; }
        /// <summary>URL that PSU will be redirected to after authorization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedirectUrl { get; set; }
#nullable restore
#else
        public string RedirectUrl { get; set; }
#endif
        /// <summary>Arbitrary string. Same string will be returned in query parameter when redirecting to the URL passed via redirect_url parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>URL that will receive POST requests notifying about payment changes. See the [webhooks documentation](../webhooks/index.md#payment-status-webhook) for more details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookUrl { get; set; }
#nullable restore
#else
        public string WebhookUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest"/> and sets the default values.
        /// </summary>
        public CreatePaymentRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aspsp", n => { Aspsp = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSP>(global::Lyra.Core.EnableBanking.Models.ASPSP.CreateFromDiscriminatorValue); } },
                { "auth_method", n => { AuthMethod = n.GetStringValue(); } },
                { "credentials", n => { Credentials = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest_credentials>(global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest_credentials.CreateFromDiscriminatorValue); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "payment_request", n => { PaymentRequest = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PaymentRequestResource>(global::Lyra.Core.EnableBanking.Models.PaymentRequestResource.CreateFromDiscriminatorValue); } },
                { "payment_type", n => { PaymentType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentType>(); } },
                { "psu_id", n => { PsuId = n.GetStringValue(); } },
                { "psu_type", n => { PsuType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>(); } },
                { "redirect_url", n => { RedirectUrl = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "webhook_url", n => { WebhookUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSP>("aspsp", Aspsp);
            writer.WriteStringValue("auth_method", AuthMethod);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.CreatePaymentRequest_credentials>("credentials", Credentials);
            writer.WriteStringValue("language", Language);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PaymentRequestResource>("payment_request", PaymentRequest);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentType>("payment_type", PaymentType);
            writer.WriteStringValue("psu_id", PsuId);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>("psu_type", PsuType);
            writer.WriteStringValue("redirect_url", RedirectUrl);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("webhook_url", WebhookUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
