// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Details of the payment instruction executed (to be executed) by the ASPSP
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreditTransferTransactionDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specification of a beneficiary</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.Beneficiary? Beneficiary { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.Beneficiary Beneficiary { get; set; }
#endif
        /// <summary>The last applicable day of execution for a given standing order.If not given, the standing order is considered as endless.</summary>
        public Date? EndDate { get; set; }
        /// <summary>Execution date shifting rule for standing orders</summary>
        public global::Lyra.Core.EnableBanking.Models.ExecutionRule? ExecutionRule { get; set; }
        /// <summary>Frequency rule for standing orders</summary>
        public global::Lyra.Core.EnableBanking.Models.FrequencyCode? Frequency { get; set; }
        /// <summary>Structure aiming to embed the amount and the currency to be used</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AmountType? InstructedAmount { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AmountType InstructedAmount { get; set; }
#endif
        /// <summary>Set of elements used to reference a payment instruction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PaymentIdentification? PaymentId { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PaymentIdentification PaymentId { get; set; }
#endif
        /// <summary>This field specifies the reference assigned by the sender to unambiguously identify the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReferenceNumber { get; set; }
#nullable restore
#else
        public string ReferenceNumber { get; set; }
#endif
        /// <summary>List of needed regulatory reporting codes for international payments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.RegulatoryReporting>? RegulatoryReporting { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.RegulatoryReporting> RegulatoryReporting { get; set; }
#endif
        /// <summary>Payment details. For credit transfers may contain free text, reference number or both at the same time (in case Extended Remittance Information is supported). When it is known that remittance information contains a reference number (either based on ISO 11649 or a local scheme), the reference number is also available via the `referenceNumber` field of the `Transaction` data structure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RemittanceInformation { get; set; }
#nullable restore
#else
        public List<string> RemittanceInformation { get; set; }
#endif
        /// <summary>Date at which the initiating party requests the clearing agent to process the payment.API:This date can be used in the following cases:- the single requested execution date for a payment having several instructions. In this case, this field must be set at the payment level.- the requested execution date for a given instruction within a payment. In this case, this field must be set at each instruction level.- The first date of execution for a standing order.When the payment cannot be processed at this date, the ASPSP is allowed to shift the applied execution date to the next possible execution date for non-standing orders.For standing orders, the [executionRule] parameter helps to compute the execution date to be applied.</summary>
        public Date? RequestedExecutionDate { get; set; }
        /// <summary>Unique identifier of the payment transaction, which can be used for fetching details through the get payment transaction endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionId { get; set; }
#nullable restore
#else
        public string TransactionId { get; set; }
#endif
        /// <summary>Status of the payment transaction</summary>
        public global::Lyra.Core.EnableBanking.Models.PaymentStatus? TransactionStatus { get; set; }
        /// <summary>Identifies the final party receiving the funds in the payment transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification? UltimateCreditor { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification UltimateCreditor { get; set; }
#endif
        /// <summary>Identifies the original party from whom the funds originate in the payment transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification? UltimateDebtor { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification UltimateDebtor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.CreditTransferTransactionDetails"/> and sets the default values.
        /// </summary>
        public CreditTransferTransactionDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.CreditTransferTransactionDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.CreditTransferTransactionDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.CreditTransferTransactionDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "beneficiary", n => { Beneficiary = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.Beneficiary>(global::Lyra.Core.EnableBanking.Models.Beneficiary.CreateFromDiscriminatorValue); } },
                { "end_date", n => { EndDate = n.GetDateValue(); } },
                { "execution_rule", n => { ExecutionRule = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.ExecutionRule>(); } },
                { "frequency", n => { Frequency = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.FrequencyCode>(); } },
                { "instructed_amount", n => { InstructedAmount = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>(global::Lyra.Core.EnableBanking.Models.AmountType.CreateFromDiscriminatorValue); } },
                { "payment_id", n => { PaymentId = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PaymentIdentification>(global::Lyra.Core.EnableBanking.Models.PaymentIdentification.CreateFromDiscriminatorValue); } },
                { "reference_number", n => { ReferenceNumber = n.GetStringValue(); } },
                { "regulatory_reporting", n => { RegulatoryReporting = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.RegulatoryReporting>(global::Lyra.Core.EnableBanking.Models.RegulatoryReporting.CreateFromDiscriminatorValue)?.AsList(); } },
                { "remittance_information", n => { RemittanceInformation = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "requested_execution_date", n => { RequestedExecutionDate = n.GetDateValue(); } },
                { "transaction_id", n => { TransactionId = n.GetStringValue(); } },
                { "transaction_status", n => { TransactionStatus = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentStatus>(); } },
                { "ultimate_creditor", n => { UltimateCreditor = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>(global::Lyra.Core.EnableBanking.Models.PartyIdentification.CreateFromDiscriminatorValue); } },
                { "ultimate_debtor", n => { UltimateDebtor = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>(global::Lyra.Core.EnableBanking.Models.PartyIdentification.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.Beneficiary>("beneficiary", Beneficiary);
            writer.WriteDateValue("end_date", EndDate);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.ExecutionRule>("execution_rule", ExecutionRule);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.FrequencyCode>("frequency", Frequency);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>("instructed_amount", InstructedAmount);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PaymentIdentification>("payment_id", PaymentId);
            writer.WriteStringValue("reference_number", ReferenceNumber);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.RegulatoryReporting>("regulatory_reporting", RegulatoryReporting);
            writer.WriteCollectionOfPrimitiveValues<string>("remittance_information", RemittanceInformation);
            writer.WriteDateValue("requested_execution_date", RequestedExecutionDate);
            writer.WriteStringValue("transaction_id", TransactionId);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentStatus>("transaction_status", TransactionStatus);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>("ultimate_creditor", UltimateCreditor);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>("ultimate_debtor", UltimateDebtor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
