// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Accounting flow of the transaction</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreditDebitIndicator
    {
        [EnumMember(Value = "CRDT")]
        #pragma warning disable CS1591
        CRDT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DBIT")]
        #pragma warning disable CS1591
        DBIT,
        #pragma warning restore CS1591
    }
}
