// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Application environment</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnvironmentObject
    {
        [EnumMember(Value = "SANDBOX")]
        #pragma warning disable CS1591
        SANDBOX,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCTION")]
        #pragma warning disable CS1591
        PRODUCTION,
        #pragma warning restore CS1591
    }
}
