// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Text error code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ErrorCode
    {
        [EnumMember(Value = "ACCESS_DENIED")]
        #pragma warning disable CS1591
        ACCESS_DENIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNT_DOES_NOT_EXIST")]
        #pragma warning disable CS1591
        ACCOUNT_DOES_NOT_EXIST,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALREADY_AUTHORIZED")]
        #pragma warning disable CS1591
        ALREADY_AUTHORIZED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ASPSP_ACCOUNT_NOT_ACCESSIBLE")]
        #pragma warning disable CS1591
        ASPSP_ACCOUNT_NOT_ACCESSIBLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ASPSP_ERROR")]
        #pragma warning disable CS1591
        ASPSP_ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "ASPSP_TIMEOUT")]
        #pragma warning disable CS1591
        ASPSP_TIMEOUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ASPSP_RATE_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        ASPSP_RATE_LIMIT_EXCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTHORIZATION_NOT_PROVIDED")]
        #pragma warning disable CS1591
        AUTHORIZATION_NOT_PROVIDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSED_SESSION")]
        #pragma warning disable CS1591
        CLOSED_SESSION,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE_TO_WITHOUT_DATE_FROM")]
        #pragma warning disable CS1591
        DATE_TO_WITHOUT_DATE_FROM,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE_FROM_IN_FUTURE")]
        #pragma warning disable CS1591
        DATE_FROM_IN_FUTURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED_AUTHORIZATION_CODE")]
        #pragma warning disable CS1591
        EXPIRED_AUTHORIZATION_CODE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED_SESSION")]
        #pragma warning disable CS1591
        EXPIRED_SESSION,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_ACCOUNT_ID")]
        #pragma warning disable CS1591
        INVALID_ACCOUNT_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_HOST")]
        #pragma warning disable CS1591
        INVALID_HOST,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNAUTHORIZED_IP")]
        #pragma warning disable CS1591
        UNAUTHORIZED_IP,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO_ACCOUNTS_ADDED")]
        #pragma warning disable CS1591
        NO_ACCOUNTS_ADDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_NOT_FOUND")]
        #pragma warning disable CS1591
        PAYMENT_NOT_FOUND,
        #pragma warning restore CS1591
        [EnumMember(Value = "PSU_HEADER_NOT_PROVIDED")]
        #pragma warning disable CS1591
        PSU_HEADER_NOT_PROVIDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PSU_HEADER_INVALID")]
        #pragma warning disable CS1591
        PSU_HEADER_INVALID,
        #pragma warning restore CS1591
        [EnumMember(Value = "REDIRECT_URI_NOT_ALLOWED")]
        #pragma warning disable CS1591
        REDIRECT_URI_NOT_ALLOWED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REVOKED_SESSION")]
        #pragma warning disable CS1591
        REVOKED_SESSION,
        #pragma warning restore CS1591
        [EnumMember(Value = "SESSION_DOES_NOT_EXIST")]
        #pragma warning disable CS1591
        SESSION_DOES_NOT_EXIST,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNAUTHORIZED_ACCESS")]
        #pragma warning disable CS1591
        UNAUTHORIZED_ACCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNTRUSTED_PAYMENT_PARTY")]
        #pragma warning disable CS1591
        UNTRUSTED_PAYMENT_PARTY,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBHOOK_URI_NOT_ALLOWED")]
        #pragma warning disable CS1591
        WEBHOOK_URI_NOT_ALLOWED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRONG_ASPSP_PROVIDED")]
        #pragma warning disable CS1591
        WRONG_ASPSP_PROVIDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRONG_AUTHORIZATION_CODE")]
        #pragma warning disable CS1591
        WRONG_AUTHORIZATION_CODE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRONG_DATE_INTERVAL")]
        #pragma warning disable CS1591
        WRONG_DATE_INTERVAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRONG_CREDENTIALS_PROVIDED")]
        #pragma warning disable CS1591
        WRONG_CREDENTIALS_PROVIDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRONG_REQUEST_PARAMETERS")]
        #pragma warning disable CS1591
        WRONG_REQUEST_PARAMETERS,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRONG_SESSION_STATUS")]
        #pragma warning disable CS1591
        WRONG_SESSION_STATUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRONG_TRANSACTIONS_PERIOD")]
        #pragma warning disable CS1591
        WRONG_TRANSACTIONS_PERIOD,
        #pragma warning restore CS1591
        [EnumMember(Value = "WRONG_CONTINUATION_KEY")]
        #pragma warning disable CS1591
        WRONG_CONTINUATION_KEY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSACTION_DOES_NOT_EXIST")]
        #pragma warning disable CS1591
        TRANSACTION_DOES_NOT_EXIST,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        PAYMENT_LIMIT_EXCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ASPSP_PAYMENT_NOT_ACCESSIBLE")]
        #pragma warning disable CS1591
        ASPSP_PAYMENT_NOT_ACCESSIBLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_PAYMENT")]
        #pragma warning disable CS1591
        INVALID_PAYMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ASPSP_PSU_ACTION_REQUIRED")]
        #pragma warning disable CS1591
        ASPSP_PSU_ACTION_REQUIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_NOT_FINALIZED")]
        #pragma warning disable CS1591
        PAYMENT_NOT_FINALIZED,
        #pragma warning restore CS1591
    }
}
