// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Provides details on the currency exchange rate and contract.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExchangeRate : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unique and unambiguous reference to the foreign exchange contract agreed between the initiating party/creditor and the debtor agent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContractIdentification { get; set; }
#nullable restore
#else
        public string ContractIdentification { get; set; }
#endif
        /// <summary>The factor used for conversion of an amount from one currency to another. This reflects the price at which one currency was bought with another currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeRateProp { get; set; }
#nullable restore
#else
        public string ExchangeRateProp { get; set; }
#endif
        /// <summary>Original amount, in which transaction was initiated. In particular, for cross-currency card transactions, the value represents original value of a purchase or a withdrawal in a currency different from the card&apos;s native or default currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AmountType? InstructedAmount { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AmountType InstructedAmount { get; set; }
#endif
        /// <summary>Specifies the type of exchange rate applied to the transaction</summary>
        public global::Lyra.Core.EnableBanking.Models.RateType? RateType { get; set; }
        /// <summary>ISO 4217 code of the currency, in which the rate of exchange is expressed in a currency exchange. In the example 1GBP = xxxCUR, the unit currency is GBP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitCurrency { get; set; }
#nullable restore
#else
        public string UnitCurrency { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.ExchangeRate"/> and sets the default values.
        /// </summary>
        public ExchangeRate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.ExchangeRate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.ExchangeRate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.ExchangeRate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contract_identification", n => { ContractIdentification = n.GetStringValue(); } },
                { "exchange_rate", n => { ExchangeRateProp = n.GetStringValue(); } },
                { "instructed_amount", n => { InstructedAmount = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>(global::Lyra.Core.EnableBanking.Models.AmountType.CreateFromDiscriminatorValue); } },
                { "rate_type", n => { RateType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.RateType>(); } },
                { "unit_currency", n => { UnitCurrency = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("contract_identification", ContractIdentification);
            writer.WriteStringValue("exchange_rate", ExchangeRateProp);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>("instructed_amount", InstructedAmount);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.RateType>("rate_type", RateType);
            writer.WriteStringValue("unit_currency", UnitCurrency);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
