// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Execution date shifting rule for standing orders</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExecutionRule
    {
        [EnumMember(Value = "FWNG")]
        #pragma warning disable CS1591
        FWNG,
        #pragma warning restore CS1591
        [EnumMember(Value = "PREC")]
        #pragma warning disable CS1591
        PREC,
        #pragma warning restore CS1591
    }
}
