// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Frequency rule for standing orders</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FrequencyCode
    {
        [EnumMember(Value = "DAIL")]
        #pragma warning disable CS1591
        DAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEEK")]
        #pragma warning disable CS1591
        WEEK,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOWK")]
        #pragma warning disable CS1591
        TOWK,
        #pragma warning restore CS1591
        [EnumMember(Value = "MNTH")]
        #pragma warning disable CS1591
        MNTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOMN")]
        #pragma warning disable CS1591
        TOMN,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUTR")]
        #pragma warning disable CS1591
        QUTR,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEMI")]
        #pragma warning disable CS1591
        SEMI,
        #pragma warning restore CS1591
        [EnumMember(Value = "YEAR")]
        #pragma warning disable CS1591
        YEAR,
        #pragma warning restore CS1591
    }
}
