// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetPaymentResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ASPSP used for the payment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.ASPSP? Aspsp { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.ASPSP Aspsp { get; set; }
#endif
        /// <summary>Indicates whether the payment has reached the status expected to be final (i.e. if the value of the field is `true`, the payment status is not expected to change on later requests)</summary>
        public bool? FinalStatus { get; set; }
        /// <summary>Payment request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PaymentRequestResourceDetails? PaymentDetails { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PaymentRequestResourceDetails PaymentDetails { get; set; }
#endif
        /// <summary>Payment ID</summary>
        public Guid? PaymentId { get; set; }
        /// <summary>Specifies the type of payment used</summary>
        public global::Lyra.Core.EnableBanking.Models.PaymentType? PaymentType { get; set; }
        /// <summary>Hashed unique identification of a PSU used by the client application. In case PSU ID is not passed by the client application, the hash is calculated based on a random value. The hash also inherits the application ID, so different hashes will be calculated when using the same PSU ID with different applications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PsuIdHash { get; set; }
#nullable restore
#else
        public string PsuIdHash { get; set; }
#endif
        /// <summary>Payment status</summary>
        public global::Lyra.Core.EnableBanking.Models.PaymentStatus? Status { get; set; }
        /// <summary>Details explaining the payment status, provided when the cause can be determined unambiguously, mainly for rejected payments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.StatusReasonInformation? StatusReasonInformation { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.StatusReasonInformation StatusReasonInformation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.GetPaymentResponse"/> and sets the default values.
        /// </summary>
        public GetPaymentResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.GetPaymentResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.GetPaymentResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.GetPaymentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aspsp", n => { Aspsp = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSP>(global::Lyra.Core.EnableBanking.Models.ASPSP.CreateFromDiscriminatorValue); } },
                { "final_status", n => { FinalStatus = n.GetBoolValue(); } },
                { "payment_details", n => { PaymentDetails = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PaymentRequestResourceDetails>(global::Lyra.Core.EnableBanking.Models.PaymentRequestResourceDetails.CreateFromDiscriminatorValue); } },
                { "payment_id", n => { PaymentId = n.GetGuidValue(); } },
                { "payment_type", n => { PaymentType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentType>(); } },
                { "psu_id_hash", n => { PsuIdHash = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentStatus>(); } },
                { "status_reason_information", n => { StatusReasonInformation = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.StatusReasonInformation>(global::Lyra.Core.EnableBanking.Models.StatusReasonInformation.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSP>("aspsp", Aspsp);
            writer.WriteBoolValue("final_status", FinalStatus);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PaymentRequestResourceDetails>("payment_details", PaymentDetails);
            writer.WriteGuidValue("payment_id", PaymentId);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentType>("payment_type", PaymentType);
            writer.WriteStringValue("psu_id_hash", PsuIdHash);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentStatus>("status", Status);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.StatusReasonInformation>("status_reason_information", StatusReasonInformation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
