// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetSessionResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Scope of access requested from ASPSP and confirmed by PSU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.Access? Access { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.Access Access { get; set; }
#endif
        /// <summary>List of account ids available in the session</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? Accounts { get; set; }
#nullable restore
#else
        public List<Guid?> Accounts { get; set; }
#endif
        /// <summary>Accounts data stored in the session</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.SessionAccount>? AccountsData { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.SessionAccount> AccountsData { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ASPSP used with the session</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.ASPSP? Aspsp { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.ASPSP Aspsp { get; set; }
#endif
        /// <summary>Date and time when the session was authorized</summary>
        public DateTimeOffset? Authorized { get; set; }
        /// <summary>Date and time when the session was closed</summary>
        public DateTimeOffset? Closed { get; set; }
        /// <summary>Date and time when the session was created</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>Hashed unique identification of a PSU used by the client application. In case PSU ID is not passed by the client application, the hash is calculated based on a random value. The hash also inherits the application ID, so different hashes will be calculated when using the same PSU ID with different applications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PsuIdHash { get; set; }
#nullable restore
#else
        public string PsuIdHash { get; set; }
#endif
        /// <summary>PSU type used with the session</summary>
        public global::Lyra.Core.EnableBanking.Models.PSUType? PsuType { get; set; }
        /// <summary>Session status</summary>
        public global::Lyra.Core.EnableBanking.Models.SessionStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.GetSessionResponse"/> and sets the default values.
        /// </summary>
        public GetSessionResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.GetSessionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.GetSessionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.GetSessionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access", n => { Access = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.Access>(global::Lyra.Core.EnableBanking.Models.Access.CreateFromDiscriminatorValue); } },
                { "accounts", n => { Accounts = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "accounts_data", n => { AccountsData = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.SessionAccount>(global::Lyra.Core.EnableBanking.Models.SessionAccount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "aspsp", n => { Aspsp = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSP>(global::Lyra.Core.EnableBanking.Models.ASPSP.CreateFromDiscriminatorValue); } },
                { "authorized", n => { Authorized = n.GetDateTimeOffsetValue(); } },
                { "closed", n => { Closed = n.GetDateTimeOffsetValue(); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "psu_id_hash", n => { PsuIdHash = n.GetStringValue(); } },
                { "psu_type", n => { PsuType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.SessionStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.Access>("access", Access);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("accounts", Accounts);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.SessionAccount>("accounts_data", AccountsData);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.ASPSP>("aspsp", Aspsp);
            writer.WriteDateTimeOffsetValue("authorized", Authorized);
            writer.WriteDateTimeOffsetValue("closed", Closed);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteStringValue("psu_id_hash", PsuIdHash);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>("psu_type", PsuType);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.SessionStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
