// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Identification of the party receiving funds in the transaction
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PartyIdentification : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies the contact details associated with a person or an organisation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.ContactDetails? ContactDetails { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.ContactDetails ContactDetails { get; set; }
#endif
        /// <summary>Name by which a party is known and which is usually used to identify that party.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Unique identification of an account, a person or an organisation, as assigned by an issuer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.GenericIdentification? OrganisationId { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.GenericIdentification OrganisationId { get; set; }
#endif
        /// <summary>Information that locates and identifies a specific address, as defined by postal services</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PostalAddress? PostalAddress { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PostalAddress PostalAddress { get; set; }
#endif
        /// <summary>Unique identification of an account, a person or an organisation, as assigned by an issuer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.GenericIdentification? PrivateId { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.GenericIdentification PrivateId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.PartyIdentification"/> and sets the default values.
        /// </summary>
        public PartyIdentification()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.PartyIdentification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.PartyIdentification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.PartyIdentification();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contact_details", n => { ContactDetails = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.ContactDetails>(global::Lyra.Core.EnableBanking.Models.ContactDetails.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organisation_id", n => { OrganisationId = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.GenericIdentification>(global::Lyra.Core.EnableBanking.Models.GenericIdentification.CreateFromDiscriminatorValue); } },
                { "postal_address", n => { PostalAddress = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PostalAddress>(global::Lyra.Core.EnableBanking.Models.PostalAddress.CreateFromDiscriminatorValue); } },
                { "private_id", n => { PrivateId = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.GenericIdentification>(global::Lyra.Core.EnableBanking.Models.GenericIdentification.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.ContactDetails>("contact_details", ContactDetails);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.GenericIdentification>("organisation_id", OrganisationId);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PostalAddress>("postal_address", PostalAddress);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.GenericIdentification>("private_id", PrivateId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
