// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Set of elements used to further specify the type of payment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentTypeInformation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies the high level purpose of the instruction based on a set of pre-defined categories. This is used by the initiating party to provide information concerning the processing of the payment. It is likely to trigger special processing by any of the agents involved in the payment chain.</summary>
        public global::Lyra.Core.EnableBanking.Models.CategoryPurposeCode? CategoryPurpose { get; set; }
        /// <summary>Indicator of the urgency or order of importance that the instructing party would like the instructed party to apply</summary>
        public global::Lyra.Core.EnableBanking.Models.PriorityCode? InstructionPriority { get; set; }
        /// <summary>User community specific instrument</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalInstrument { get; set; }
#nullable restore
#else
        public string LocalInstrument { get; set; }
#endif
        /// <summary>Agreement under which or rules under which the transaction should be processed. Specifies a pre-agreed service or level of service between the parties, as published in an external service level code list</summary>
        public global::Lyra.Core.EnableBanking.Models.ServiceLevelCode? ServiceLevel { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation"/> and sets the default values.
        /// </summary>
        public PaymentTypeInformation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "category_purpose", n => { CategoryPurpose = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.CategoryPurposeCode>(); } },
                { "instruction_priority", n => { InstructionPriority = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PriorityCode>(); } },
                { "local_instrument", n => { LocalInstrument = n.GetStringValue(); } },
                { "service_level", n => { ServiceLevel = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.ServiceLevelCode>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.CategoryPurposeCode>("category_purpose", CategoryPurpose);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PriorityCode>("instruction_priority", InstructionPriority);
            writer.WriteStringValue("local_instrument", LocalInstrument);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.ServiceLevelCode>("service_level", ServiceLevel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
