// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Payment status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentStatus
    {
        [EnumMember(Value = "ACCC")]
        #pragma warning disable CS1591
        ACCC,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCP")]
        #pragma warning disable CS1591
        ACCP,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACSC")]
        #pragma warning disable CS1591
        ACSC,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACSP")]
        #pragma warning disable CS1591
        ACSP,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTC")]
        #pragma warning disable CS1591
        ACTC,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACWC")]
        #pragma warning disable CS1591
        ACWC,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACWP")]
        #pragma warning disable CS1591
        ACWP,
        #pragma warning restore CS1591
        [EnumMember(Value = "PART")]
        #pragma warning disable CS1591
        PART,
        #pragma warning restore CS1591
        [EnumMember(Value = "RCVD")]
        #pragma warning disable CS1591
        RCVD,
        #pragma warning restore CS1591
        [EnumMember(Value = "PDNG")]
        #pragma warning disable CS1591
        PDNG,
        #pragma warning restore CS1591
        [EnumMember(Value = "RJCT")]
        #pragma warning disable CS1591
        RJCT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACPT")]
        #pragma warning disable CS1591
        ACPT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCR")]
        #pragma warning disable CS1591
        ACCR,
        #pragma warning restore CS1591
        [EnumMember(Value = "RJCR")]
        #pragma warning disable CS1591
        RJCR,
        #pragma warning restore CS1591
        [EnumMember(Value = "PACR")]
        #pragma warning disable CS1591
        PACR,
        #pragma warning restore CS1591
        [EnumMember(Value = "PDCR")]
        #pragma warning disable CS1591
        PDCR,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNCL")]
        #pragma warning disable CS1591
        CNCL,
        #pragma warning restore CS1591
        [EnumMember(Value = "NULL")]
        #pragma warning disable CS1591
        NULL,
        #pragma warning restore CS1591
    }
}
