// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Display only ASPSPs which support specified payment type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentType
    {
        [EnumMember(Value = "SEPA")]
        #pragma warning disable CS1591
        SEPA,
        #pragma warning restore CS1591
        [EnumMember(Value = "INST_SEPA")]
        #pragma warning disable CS1591
        INST_SEPA,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOMESTIC")]
        #pragma warning disable CS1591
        DOMESTIC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CROSSBORDER")]
        #pragma warning disable CS1591
        CROSSBORDER,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOMESTIC_SE_GIRO")]
        #pragma warning disable CS1591
        DOMESTIC_SE_GIRO,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTERNAL")]
        #pragma warning disable CS1591
        INTERNAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "BULK_SEPA")]
        #pragma warning disable CS1591
        BULK_SEPA,
        #pragma warning restore CS1591
        [EnumMember(Value = "BULK_DOMESTIC")]
        #pragma warning disable CS1591
        BULK_DOMESTIC,
        #pragma warning restore CS1591
        [EnumMember(Value = "BULK_DOMESTIC_SE_GIRO")]
        #pragma warning disable CS1591
        BULK_DOMESTIC_SE_GIRO,
        #pragma warning restore CS1591
    }
}
