// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Specifies the details required to initiate a payment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentRequestResource : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies which party/parties will bear the charges associated with the processing of the payment</summary>
        public global::Lyra.Core.EnableBanking.Models.ChargeBearerCode? ChargeBearer { get; set; }
        /// <summary>Payment instructions to be executed towards one or multiple beneficiaries in the payment process. Maximum number of transactions depend on the ASPSP and type of the payment taking into accounts its specificities about payment request handling.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.CreditTransferTransaction>? CreditTransferTransaction { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.CreditTransferTransaction> CreditTransferTransaction { get; set; }
#endif
        /// <summary>Identification of the party sending funds</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification? Debtor { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification Debtor { get; set; }
#endif
        /// <summary>Identification of the account from which funds are sent when the payment is executed. When the debtor account is not provided it is to be chosen by the PSU during payment authorisation flow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.GenericIdentification? DebtorAccount { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.GenericIdentification DebtorAccount { get; set; }
#endif
        /// <summary>Identification of the financial institution where the debtor account is held. To be provided only in case the financial institution can not be unambiguously identified the ASPSP name towards which the payment is initiated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification? DebtorAgent { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification DebtorAgent { get; set; }
#endif
        /// <summary>ISO 4217 code, in which debtor account is held</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DebtorCurrency { get; set; }
#nullable restore
#else
        public string DebtorCurrency { get; set; }
#endif
        /// <summary>Reference assigned by a sending party to unambiguously identify the payment information block within the message</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentInformationId { get; set; }
#nullable restore
#else
        public string PaymentInformationId { get; set; }
#endif
        /// <summary>Set of elements used to further specify the type of payment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation? PaymentTypeInformation { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation PaymentTypeInformation { get; set; }
#endif
        /// <summary>Underlying reason for the payment</summary>
        public global::Lyra.Core.EnableBanking.Models.PurposeCode? Purpose { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.PaymentRequestResource"/> and sets the default values.
        /// </summary>
        public PaymentRequestResource()
        {
            AdditionalData = new Dictionary<string, object>();
            DebtorCurrency = "XXX";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.PaymentRequestResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.PaymentRequestResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.PaymentRequestResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "charge_bearer", n => { ChargeBearer = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.ChargeBearerCode>(); } },
                { "credit_transfer_transaction", n => { CreditTransferTransaction = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.CreditTransferTransaction>(global::Lyra.Core.EnableBanking.Models.CreditTransferTransaction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "debtor", n => { Debtor = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>(global::Lyra.Core.EnableBanking.Models.PartyIdentification.CreateFromDiscriminatorValue); } },
                { "debtor_account", n => { DebtorAccount = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.GenericIdentification>(global::Lyra.Core.EnableBanking.Models.GenericIdentification.CreateFromDiscriminatorValue); } },
                { "debtor_agent", n => { DebtorAgent = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>(global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification.CreateFromDiscriminatorValue); } },
                { "debtor_currency", n => { DebtorCurrency = n.GetStringValue(); } },
                { "payment_information_id", n => { PaymentInformationId = n.GetStringValue(); } },
                { "payment_type_information", n => { PaymentTypeInformation = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation>(global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation.CreateFromDiscriminatorValue); } },
                { "purpose", n => { Purpose = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PurposeCode>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.ChargeBearerCode>("charge_bearer", ChargeBearer);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.CreditTransferTransaction>("credit_transfer_transaction", CreditTransferTransaction);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>("debtor", Debtor);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.GenericIdentification>("debtor_account", DebtorAccount);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>("debtor_agent", DebtorAgent);
            writer.WriteStringValue("debtor_currency", DebtorCurrency);
            writer.WriteStringValue("payment_information_id", PaymentInformationId);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PaymentTypeInformation>("payment_type_information", PaymentTypeInformation);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PurposeCode>("purpose", Purpose);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
