// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Information that locates and identifies a specific address, as defined by postal services
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostalAddress : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unstructured address. The two lines must embed zip code and town name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AddressLine { get; set; }
#nullable restore
#else
        public List<string> AddressLine { get; set; }
#endif
        /// <summary>Available address type values</summary>
        public global::Lyra.Core.EnableBanking.Models.AddressType? AddressType { get; set; }
        /// <summary>Number that identifies the position of a building on a street.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuildingNumber { get; set; }
#nullable restore
#else
        public string BuildingNumber { get; set; }
#endif
        /// <summary>Two-letter ISO 3166 code of the country in which a person resides (the place of a person&apos;s home). In the case of a company, it is the country from which the affairs of that company are directed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>Identifies a subdivision of a country such as state, region, county.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountrySubDivision { get; set; }
#nullable restore
#else
        public string CountrySubDivision { get; set; }
#endif
        /// <summary>Identification of a division of a large organisation or building.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Department { get; set; }
#nullable restore
#else
        public string Department { get; set; }
#endif
        /// <summary>Identifier consisting of a group of letters and/or numbers that isadded to a postal address to assist the sorting of mail.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostCode { get; set; }
#nullable restore
#else
        public string PostCode { get; set; }
#endif
        /// <summary>Name of a street or thoroughfare.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetName { get; set; }
#nullable restore
#else
        public string StreetName { get; set; }
#endif
        /// <summary>Identification of a sub-division of a large organisation or building.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubDepartment { get; set; }
#nullable restore
#else
        public string SubDepartment { get; set; }
#endif
        /// <summary>Name of a built-up area, with defined boundaries, and a local government.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TownName { get; set; }
#nullable restore
#else
        public string TownName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.PostalAddress"/> and sets the default values.
        /// </summary>
        public PostalAddress()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.PostalAddress"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.PostalAddress CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.PostalAddress();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_line", n => { AddressLine = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "address_type", n => { AddressType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.AddressType>(); } },
                { "building_number", n => { BuildingNumber = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "country_sub_division", n => { CountrySubDivision = n.GetStringValue(); } },
                { "department", n => { Department = n.GetStringValue(); } },
                { "post_code", n => { PostCode = n.GetStringValue(); } },
                { "street_name", n => { StreetName = n.GetStringValue(); } },
                { "sub_department", n => { SubDepartment = n.GetStringValue(); } },
                { "town_name", n => { TownName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("address_line", AddressLine);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.AddressType>("address_type", AddressType);
            writer.WriteStringValue("building_number", BuildingNumber);
            writer.WriteStringValue("country", Country);
            writer.WriteStringValue("country_sub_division", CountrySubDivision);
            writer.WriteStringValue("department", Department);
            writer.WriteStringValue("post_code", PostCode);
            writer.WriteStringValue("street_name", StreetName);
            writer.WriteStringValue("sub_department", SubDepartment);
            writer.WriteStringValue("town_name", TownName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
