// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PriorityCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "HIGH")]
        #pragma warning disable CS1591
        HIGH,
        #pragma warning restore CS1591
        [EnumMember(Value = "NORM")]
        #pragma warning disable CS1591
        NORM,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPR")]
        #pragma warning disable CS1591
        EXPR,
        #pragma warning restore CS1591
    }
}
