// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Display only ASPSPs which support specified psu type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PSUType
    {
        [EnumMember(Value = "business")]
        #pragma warning disable CS1591
        Business,
        #pragma warning restore CS1591
        [EnumMember(Value = "personal")]
        #pragma warning disable CS1591
        Personal,
        #pragma warning restore CS1591
    }
}
