// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Underlying reason for the payment</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PurposeCode
    {
        [EnumMember(Value = "ACCT")]
        #pragma warning disable CS1591
        ACCT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASH")]
        #pragma warning disable CS1591
        CASH,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMC")]
        #pragma warning disable CS1591
        COMC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CPKC")]
        #pragma warning disable CS1591
        CPKC,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRPT")]
        #pragma warning disable CS1591
        TRPT,
        #pragma warning restore CS1591
    }
}
