// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Specifies the type of exchange rate applied to the transaction</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RateType
    {
        [EnumMember(Value = "SPOT")]
        #pragma warning disable CS1591
        SPOT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SALE")]
        #pragma warning disable CS1591
        SALE,
        #pragma warning restore CS1591
        [EnumMember(Value = "AGRD")]
        #pragma warning disable CS1591
        AGRD,
        #pragma warning restore CS1591
    }
}
