// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ReferenceNumberScheme
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SEBG")]
        #pragma warning disable CS1591
        SEBG,
        #pragma warning restore CS1591
        [EnumMember(Value = "NORF")]
        #pragma warning disable CS1591
        NORF,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIRF")]
        #pragma warning disable CS1591
        FIRF,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTL")]
        #pragma warning disable CS1591
        INTL,
        #pragma warning restore CS1591
        [EnumMember(Value = "BERF")]
        #pragma warning disable CS1591
        BERF,
        #pragma warning restore CS1591
        [EnumMember(Value = "SDDM")]
        #pragma warning disable CS1591
        SDDM,
        #pragma warning restore CS1591
    }
}
