// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResponsePaymentType : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of supported auth methods for this payment type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedAuthMethods { get; set; }
#nullable restore
#else
        public List<string> AllowedAuthMethods { get; set; }
#endif
        /// <summary>List of supported charge bearer codes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.ChargeBearerCode?>? ChargeBearerValues { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.ChargeBearerCode?> ChargeBearerValues { get; set; }
#endif
        /// <summary>List of supported creditor account schemas</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.SchemeName?>? CreditorAccountSchemas { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.SchemeName?> CreditorAccountSchemas { get; set; }
#endif
        /// <summary>States if creditor agent bicFi is required. Create payment body field: `payment_request.credit_transfer_transaction[*].beneficiary.creditor_agent.bic_fi`</summary>
        public bool? CreditorAgentBicFiRequired { get; set; }
        /// <summary>States if creditor agent clearing system member ID is required. Create payment body field: `payment_request.credit_transfer_transaction[*].beneficiary.creditor_agent.clearing_system_member_id`</summary>
        public bool? CreditorAgentClearingSystemMemberIdRequired { get; set; }
        /// <summary>States if creditor country is required. Create payment body field: `payment_request.credit_transfer_transaction[*].beneficiary.creditor.postal_address.country`</summary>
        public bool? CreditorCountryRequired { get; set; }
        /// <summary>States if creditor name is required.  Create payment body field: `payment_request.credit_transfer_transaction[*].beneficiary.creditor.postal_address.country`</summary>
        public bool? CreditorNameRequired { get; set; }
        /// <summary>States if creditor postal address is required. Create payment body field: `payment_request.credit_transfer_transaction[*].beneficiary.creditor.postal_address`</summary>
        public bool? CreditorPostalAddressRequired { get; set; }
        /// <summary>List of supported currencies</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Currencies { get; set; }
#nullable restore
#else
        public List<string> Currencies { get; set; }
#endif
        /// <summary>States if debtor account is required for payment initiation request. When the debtor account is not provided it is to be chosen by the PSU during payment authorisation flow. Create payment body field: `payment_request.debtor_account`</summary>
        public bool? DebtorAccountRequired { get; set; }
        /// <summary>List of supported debtor account schemas</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.SchemeName?>? DebtorAccountSchemas { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.SchemeName?> DebtorAccountSchemas { get; set; }
#endif
        /// <summary>States if debtor&apos;s contact email is required when a payment this type is being initiated. Create payment body field: `payment_request.debtor.contact_details.email_address`</summary>
        public bool? DebtorContactEmailRequired { get; set; }
        /// <summary>States if debtor&apos;s contact phone is required when a payment this type is being initiated. Create payment body field: `payment_request.debtor.contact_details.phone_number`</summary>
        public bool? DebtorContactPhoneRequired { get; set; }
        /// <summary>States if debtor currency is required. Create payment body field: `payment_request.debtor_currency`</summary>
        public bool? DebtorCurrencyRequired { get; set; }
        /// <summary>List of the final successful statuses for the payment type. Please note that when a payment reaches one of the statuses provided in this list, it is not yet guaranteed that the funds will be credited to the creditor&apos;s account specified in the payment request. It is up to the application that created the payment to conclude whether the funds are (or will be) received, depending on the actual payment status and other factors.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.PaymentStatus?>? FinalSuccessfulStatuses { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.PaymentStatus?> FinalSuccessfulStatuses { get; set; }
#endif
        /// <summary>Maximum number of transactions per payment</summary>
        public int? MaxTransactions { get; set; }
        /// <summary>Payment type name</summary>
        public global::Lyra.Core.EnableBanking.Models.PaymentType? PaymentType { get; set; }
        /// <summary>List of supported priority codes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.PriorityCode?>? PriorityCodes { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.PriorityCode?> PriorityCodes { get; set; }
#endif
        /// <summary>PSU type</summary>
        public global::Lyra.Core.EnableBanking.Models.PSUType? PsuType { get; set; }
        /// <summary>List of reference number schemas supported by a payment method</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.ReferenceNumberScheme?>? ReferenceNumberSchemas { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.ReferenceNumberScheme?> ReferenceNumberSchemas { get; set; }
#endif
        /// <summary>States if reference number can be provided for credit transfer transactions</summary>
        public bool? ReferenceNumberSupported { get; set; }
        /// <summary>States if regulatory reporting shall be provided for credit transfer transactions. Create payment body field: `payment_request.credit_transfer_transaction[*].regulatory_reporting.details.code`</summary>
        public bool? RegulatoryReportingCodeRequired { get; set; }
        /// <summary>List of supported codes for regulatory reporting details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.RegulatoryReportingCode>? RegulatoryReportingCodes { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.RegulatoryReportingCode> RegulatoryReportingCodes { get; set; }
#endif
        /// <summary>Properties of remittance information. Each item of the array correspond to the remittance information line with the same index. When provided, the number of lines in the remittance information should be the same as the length of this array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.RemittanceInformationLineInfo>? RemittanceInformationLines { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.RemittanceInformationLineInfo> RemittanceInformationLines { get; set; }
#endif
        /// <summary>States if remittance information is required. Create payment body field: `payment_request.credit_transfer_transaction[*].remittance_information`</summary>
        public bool? RemittanceInformationRequired { get; set; }
        /// <summary>States if both reference number and remittance information can be provided simultaneously</summary>
        public bool? RemittanceReferenceSupported { get; set; }
        /// <summary>Maximum requested execution date interval in the future</summary>
        public int? RequestedExecutionDateMaxPeriod { get; set; }
        /// <summary>States if requested execution date supported by a payment method</summary>
        public bool? RequestedExecutionDateSupported { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.ResponsePaymentType"/> and sets the default values.
        /// </summary>
        public ResponsePaymentType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.ResponsePaymentType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.ResponsePaymentType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.ResponsePaymentType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_auth_methods", n => { AllowedAuthMethods = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "charge_bearer_values", n => { ChargeBearerValues = n.GetCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.ChargeBearerCode>()?.AsList(); } },
                { "creditor_account_schemas", n => { CreditorAccountSchemas = n.GetCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.SchemeName>()?.AsList(); } },
                { "creditor_agent_bic_fi_required", n => { CreditorAgentBicFiRequired = n.GetBoolValue(); } },
                { "creditor_agent_clearing_system_member_id_required", n => { CreditorAgentClearingSystemMemberIdRequired = n.GetBoolValue(); } },
                { "creditor_country_required", n => { CreditorCountryRequired = n.GetBoolValue(); } },
                { "creditor_name_required", n => { CreditorNameRequired = n.GetBoolValue(); } },
                { "creditor_postal_address_required", n => { CreditorPostalAddressRequired = n.GetBoolValue(); } },
                { "currencies", n => { Currencies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "debtor_account_required", n => { DebtorAccountRequired = n.GetBoolValue(); } },
                { "debtor_account_schemas", n => { DebtorAccountSchemas = n.GetCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.SchemeName>()?.AsList(); } },
                { "debtor_contact_email_required", n => { DebtorContactEmailRequired = n.GetBoolValue(); } },
                { "debtor_contact_phone_required", n => { DebtorContactPhoneRequired = n.GetBoolValue(); } },
                { "debtor_currency_required", n => { DebtorCurrencyRequired = n.GetBoolValue(); } },
                { "final_successful_statuses", n => { FinalSuccessfulStatuses = n.GetCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.PaymentStatus>()?.AsList(); } },
                { "max_transactions", n => { MaxTransactions = n.GetIntValue(); } },
                { "payment_type", n => { PaymentType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentType>(); } },
                { "priority_codes", n => { PriorityCodes = n.GetCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.PriorityCode>()?.AsList(); } },
                { "psu_type", n => { PsuType = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>(); } },
                { "reference_number_schemas", n => { ReferenceNumberSchemas = n.GetCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.ReferenceNumberScheme>()?.AsList(); } },
                { "reference_number_supported", n => { ReferenceNumberSupported = n.GetBoolValue(); } },
                { "regulatory_reporting_code_required", n => { RegulatoryReportingCodeRequired = n.GetBoolValue(); } },
                { "regulatory_reporting_codes", n => { RegulatoryReportingCodes = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.RegulatoryReportingCode>(global::Lyra.Core.EnableBanking.Models.RegulatoryReportingCode.CreateFromDiscriminatorValue)?.AsList(); } },
                { "remittance_information_lines", n => { RemittanceInformationLines = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.RemittanceInformationLineInfo>(global::Lyra.Core.EnableBanking.Models.RemittanceInformationLineInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "remittance_information_required", n => { RemittanceInformationRequired = n.GetBoolValue(); } },
                { "remittance_reference_supported", n => { RemittanceReferenceSupported = n.GetBoolValue(); } },
                { "requested_execution_date_max_period", n => { RequestedExecutionDateMaxPeriod = n.GetIntValue(); } },
                { "requested_execution_date_supported", n => { RequestedExecutionDateSupported = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_auth_methods", AllowedAuthMethods);
            writer.WriteCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.ChargeBearerCode>("charge_bearer_values", ChargeBearerValues);
            writer.WriteCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.SchemeName>("creditor_account_schemas", CreditorAccountSchemas);
            writer.WriteBoolValue("creditor_agent_bic_fi_required", CreditorAgentBicFiRequired);
            writer.WriteBoolValue("creditor_agent_clearing_system_member_id_required", CreditorAgentClearingSystemMemberIdRequired);
            writer.WriteBoolValue("creditor_country_required", CreditorCountryRequired);
            writer.WriteBoolValue("creditor_name_required", CreditorNameRequired);
            writer.WriteBoolValue("creditor_postal_address_required", CreditorPostalAddressRequired);
            writer.WriteCollectionOfPrimitiveValues<string>("currencies", Currencies);
            writer.WriteBoolValue("debtor_account_required", DebtorAccountRequired);
            writer.WriteCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.SchemeName>("debtor_account_schemas", DebtorAccountSchemas);
            writer.WriteBoolValue("debtor_contact_email_required", DebtorContactEmailRequired);
            writer.WriteBoolValue("debtor_contact_phone_required", DebtorContactPhoneRequired);
            writer.WriteBoolValue("debtor_currency_required", DebtorCurrencyRequired);
            writer.WriteCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.PaymentStatus>("final_successful_statuses", FinalSuccessfulStatuses);
            writer.WriteIntValue("max_transactions", MaxTransactions);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PaymentType>("payment_type", PaymentType);
            writer.WriteCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.PriorityCode>("priority_codes", PriorityCodes);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.PSUType>("psu_type", PsuType);
            writer.WriteCollectionOfEnumValues<global::Lyra.Core.EnableBanking.Models.ReferenceNumberScheme>("reference_number_schemas", ReferenceNumberSchemas);
            writer.WriteBoolValue("reference_number_supported", ReferenceNumberSupported);
            writer.WriteBoolValue("regulatory_reporting_code_required", RegulatoryReportingCodeRequired);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.RegulatoryReportingCode>("regulatory_reporting_codes", RegulatoryReportingCodes);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.RemittanceInformationLineInfo>("remittance_information_lines", RemittanceInformationLines);
            writer.WriteBoolValue("remittance_information_required", RemittanceInformationRequired);
            writer.WriteBoolValue("remittance_reference_supported", RemittanceReferenceSupported);
            writer.WriteIntValue("requested_execution_date_max_period", RequestedExecutionDateMaxPeriod);
            writer.WriteBoolValue("requested_execution_date_supported", RequestedExecutionDateSupported);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
