// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Name of the identification scheme. Partially based on ISO20022 external code list</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SchemeName
    {
        [EnumMember(Value = "CHID")]
        #pragma warning disable CS1591
        CHID,
        #pragma warning restore CS1591
        [EnumMember(Value = "GS1G")]
        #pragma warning disable CS1591
        GS1G,
        #pragma warning restore CS1591
        [EnumMember(Value = "DUNS")]
        #pragma warning disable CS1591
        DUNS,
        #pragma warning restore CS1591
        [EnumMember(Value = "BANK")]
        #pragma warning disable CS1591
        BANK,
        #pragma warning restore CS1591
        [EnumMember(Value = "TXID")]
        #pragma warning disable CS1591
        TXID,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUST")]
        #pragma warning disable CS1591
        CUST,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMPL")]
        #pragma warning disable CS1591
        EMPL,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHC")]
        #pragma warning disable CS1591
        OTHC,
        #pragma warning restore CS1591
        [EnumMember(Value = "DRLC")]
        #pragma warning disable CS1591
        DRLC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSI")]
        #pragma warning disable CS1591
        CUSI,
        #pragma warning restore CS1591
        [EnumMember(Value = "SOSE")]
        #pragma warning disable CS1591
        SOSE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARNU")]
        #pragma warning disable CS1591
        ARNU,
        #pragma warning restore CS1591
        [EnumMember(Value = "CCPT")]
        #pragma warning disable CS1591
        CCPT,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHI")]
        #pragma warning disable CS1591
        OTHI,
        #pragma warning restore CS1591
        [EnumMember(Value = "COID")]
        #pragma warning disable CS1591
        COID,
        #pragma warning restore CS1591
        [EnumMember(Value = "SREN")]
        #pragma warning disable CS1591
        SREN,
        #pragma warning restore CS1591
        [EnumMember(Value = "SRET")]
        #pragma warning disable CS1591
        SRET,
        #pragma warning restore CS1591
        [EnumMember(Value = "NIDN")]
        #pragma warning disable CS1591
        NIDN,
        #pragma warning restore CS1591
        [EnumMember(Value = "OAUT")]
        #pragma warning disable CS1591
        OAUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CPAN")]
        #pragma warning disable CS1591
        CPAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "BBAN")]
        #pragma warning disable CS1591
        BBAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "IBAN")]
        #pragma warning disable CS1591
        IBAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "MIBN")]
        #pragma warning disable CS1591
        MIBN,
        #pragma warning restore CS1591
        [EnumMember(Value = "BGNR")]
        #pragma warning disable CS1591
        BGNR,
        #pragma warning restore CS1591
        [EnumMember(Value = "PGNR")]
        #pragma warning disable CS1591
        PGNR,
        #pragma warning restore CS1591
    }
}
