// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Agreement under which or rules under which the transaction should be processed. Specifies a pre-agreed service or level of service between the parties, as published in an external service level code list</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ServiceLevelCode
    {
        [EnumMember(Value = "BKTR")]
        #pragma warning disable CS1591
        BKTR,
        #pragma warning restore CS1591
        [EnumMember(Value = "G001")]
        #pragma warning disable CS1591
        G001,
        #pragma warning restore CS1591
        [EnumMember(Value = "G002")]
        #pragma warning disable CS1591
        G002,
        #pragma warning restore CS1591
        [EnumMember(Value = "G003")]
        #pragma warning disable CS1591
        G003,
        #pragma warning restore CS1591
        [EnumMember(Value = "G004")]
        #pragma warning disable CS1591
        G004,
        #pragma warning restore CS1591
        [EnumMember(Value = "NUGP")]
        #pragma warning disable CS1591
        NUGP,
        #pragma warning restore CS1591
        [EnumMember(Value = "NURG")]
        #pragma warning disable CS1591
        NURG,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRPT")]
        #pragma warning disable CS1591
        PRPT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SDVA")]
        #pragma warning disable CS1591
        SDVA,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEPA")]
        #pragma warning disable CS1591
        SEPA,
        #pragma warning restore CS1591
        [EnumMember(Value = "SVDE")]
        #pragma warning disable CS1591
        SVDE,
        #pragma warning restore CS1591
        [EnumMember(Value = "URGP")]
        #pragma warning disable CS1591
        URGP,
        #pragma warning restore CS1591
        [EnumMember(Value = "URNS")]
        #pragma warning disable CS1591
        URNS,
        #pragma warning restore CS1591
    }
}
