// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Display only ASPSPs which support specified service</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Service
    {
        [EnumMember(Value = "AIS")]
        #pragma warning disable CS1591
        AIS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PIS")]
        #pragma warning disable CS1591
        PIS,
        #pragma warning restore CS1591
    }
}
