// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Session status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SessionStatus
    {
        [EnumMember(Value = "INVALID")]
        #pragma warning disable CS1591
        INVALID,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_AUTHORIZATION")]
        #pragma warning disable CS1591
        PENDING_AUTHORIZATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "RETURNED_FROM_BANK")]
        #pragma warning disable CS1591
        RETURNED_FROM_BANK,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTHORIZED")]
        #pragma warning disable CS1591
        AUTHORIZED,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        EXPIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSED")]
        #pragma warning disable CS1591
        CLOSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REVOKED")]
        #pragma warning disable CS1591
        REVOKED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        CANCELLED,
        #pragma warning restore CS1591
    }
}
