// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>
    /// Details explaining the payment status, provided when the cause can be determined unambiguously, mainly for rejected payments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusReasonInformation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ISO20022 status reason code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReasonCode { get; set; }
#nullable restore
#else
        public string StatusReasonCode { get; set; }
#endif
        /// <summary>Status reason description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReasonDescription { get; set; }
#nullable restore
#else
        public string StatusReasonDescription { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.StatusReasonInformation"/> and sets the default values.
        /// </summary>
        public StatusReasonInformation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.StatusReasonInformation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.StatusReasonInformation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.StatusReasonInformation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "status_reason_code", n => { StatusReasonCode = n.GetStringValue(); } },
                { "status_reason_description", n => { StatusReasonDescription = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("status_reason_code", StatusReasonCode);
            writer.WriteStringValue("status_reason_description", StatusReasonDescription);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
