// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TransactionStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BOOK")]
        #pragma warning disable CS1591
        BOOK,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNCL")]
        #pragma warning disable CS1591
        CNCL,
        #pragma warning restore CS1591
        [EnumMember(Value = "HOLD")]
        #pragma warning disable CS1591
        HOLD,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHR")]
        #pragma warning disable CS1591
        OTHR,
        #pragma warning restore CS1591
        [EnumMember(Value = "PDNG")]
        #pragma warning disable CS1591
        PDNG,
        #pragma warning restore CS1591
        [EnumMember(Value = "RJCT")]
        #pragma warning disable CS1591
        RJCT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHD")]
        #pragma warning disable CS1591
        SCHD,
        #pragma warning restore CS1591
    }
}
