// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Transaction : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Funds on the account after execution of the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AmountType? BalanceAfterTransaction { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AmountType BalanceAfterTransaction { get; set; }
#endif
        /// <summary>Allows the account servicer to correctly report a transaction, which in its turn will help account holders to perform their cash management and reconciliation operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.BankTransactionCode? BankTransactionCode { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.BankTransactionCode BankTransactionCode { get; set; }
#endif
        /// <summary>Booking date of the transaction on the account, i.e. the date at which the transaction has been recorded on books</summary>
        public Date? BookingDate { get; set; }
        /// <summary>Accounting flow of the transaction</summary>
        public global::Lyra.Core.EnableBanking.Models.CreditDebitIndicator? CreditDebitIndicator { get; set; }
        /// <summary>Identification of the party receiving funds in the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification? Creditor { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification Creditor { get; set; }
#endif
        /// <summary>Identification of the account on which the transaction is credited</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AccountIdentification? CreditorAccount { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AccountIdentification CreditorAccount { get; set; }
#endif
        /// <summary>All other creditor account identifiers provided by ASPSPs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.GenericIdentification>? CreditorAccountAdditionalIdentification { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.GenericIdentification> CreditorAccountAdditionalIdentification { get; set; }
#endif
        /// <summary>Identification of the creditor agent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification? CreditorAgent { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification CreditorAgent { get; set; }
#endif
        /// <summary>Identification of the party sending funds in the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification? Debtor { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.PartyIdentification Debtor { get; set; }
#endif
        /// <summary>Identification of the account on which the transaction is debited</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AccountIdentification? DebtorAccount { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AccountIdentification DebtorAccount { get; set; }
#endif
        /// <summary>All other debtor account identifiers provided by ASPSPs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Lyra.Core.EnableBanking.Models.GenericIdentification>? DebtorAccountAdditionalIdentification { get; set; }
#nullable restore
#else
        public List<global::Lyra.Core.EnableBanking.Models.GenericIdentification> DebtorAccountAdditionalIdentification { get; set; }
#endif
        /// <summary>Identification of the debtor agent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification? DebtorAgent { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification DebtorAgent { get; set; }
#endif
        /// <summary>Unique transaction identifier provided by ASPSP. This identifier is both unique and immutable for accounts with the same identification hashes and can be used for matching transactions across multiple PSU authentication sessions. Usually the same identifier is available for transactions in ASPSP&apos;s online/mobile interface and is called archive ID or similarly. Please note that this identifier is not globally unique and same entry references are likely to occur for transactions belonging to different accounts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntryReference { get; set; }
#nullable restore
#else
        public string EntryReference { get; set; }
#endif
        /// <summary>Provides details on the currency exchange rate and contract.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.ExchangeRate? ExchangeRate { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.ExchangeRate ExchangeRate { get; set; }
#endif
        /// <summary>Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantCategoryCode { get; set; }
#nullable restore
#else
        public string MerchantCategoryCode { get; set; }
#endif
        /// <summary>The internal note made by PSU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>Credit transfer reference number (also known as the creditor reference or the structured creditor reference). The value is set when it is known that the transaction data contains a reference number (in either ISO 11649 or another format). If the format is known it is provided in the reference_number_schema field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReferenceNumber { get; set; }
#nullable restore
#else
        public string ReferenceNumber { get; set; }
#endif
        /// <summary>Indicates what kind of reference number is used.</summary>
        public global::Lyra.Core.EnableBanking.Models.ReferenceNumberScheme? ReferenceNumberSchema { get; set; }
        /// <summary>Payment details. For credit transfers may contain free text, reference number or both at the same time (in case Extended Remittance Information is supported). When it is known that remittance information contains a reference number (either based on ISO 11649 or a local scheme), the reference number is also available via the `reference_number` field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RemittanceInformation { get; set; }
#nullable restore
#else
        public List<string> RemittanceInformation { get; set; }
#endif
        /// <summary>Available transaction status values</summary>
        public global::Lyra.Core.EnableBanking.Models.TransactionStatus? Status { get; set; }
        /// <summary>Monetary sum of the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Lyra.Core.EnableBanking.Models.AmountType? TransactionAmount { get; set; }
#nullable restore
#else
        public global::Lyra.Core.EnableBanking.Models.AmountType TransactionAmount { get; set; }
#endif
        /// <summary>Date used for specific purposes:- for card transaction: date of the transaction- for credit transfer: acquiring date of the transaction- for direct debit: receiving date of the transaction</summary>
        public Date? TransactionDate { get; set; }
        /// <summary>Identification used for fetching transaction details.This value can not be used to uniquely identify transactions and may change if the list of transactions is retrieved again. Null if fetching transaction details is not supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionId { get; set; }
#nullable restore
#else
        public string TransactionId { get; set; }
#endif
        /// <summary>Value date of the transaction on the account, i.e. the date at which funds become available to the account holder (in case of a credit transaction), or cease to be available to the account holder (in case of a debit transaction)</summary>
        public Date? ValueDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Lyra.Core.EnableBanking.Models.Transaction"/> and sets the default values.
        /// </summary>
        public Transaction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Lyra.Core.EnableBanking.Models.Transaction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Lyra.Core.EnableBanking.Models.Transaction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Lyra.Core.EnableBanking.Models.Transaction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "balance_after_transaction", n => { BalanceAfterTransaction = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>(global::Lyra.Core.EnableBanking.Models.AmountType.CreateFromDiscriminatorValue); } },
                { "bank_transaction_code", n => { BankTransactionCode = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.BankTransactionCode>(global::Lyra.Core.EnableBanking.Models.BankTransactionCode.CreateFromDiscriminatorValue); } },
                { "booking_date", n => { BookingDate = n.GetDateValue(); } },
                { "credit_debit_indicator", n => { CreditDebitIndicator = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.CreditDebitIndicator>(); } },
                { "creditor", n => { Creditor = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>(global::Lyra.Core.EnableBanking.Models.PartyIdentification.CreateFromDiscriminatorValue); } },
                { "creditor_account", n => { CreditorAccount = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AccountIdentification>(global::Lyra.Core.EnableBanking.Models.AccountIdentification.CreateFromDiscriminatorValue); } },
                { "creditor_account_additional_identification", n => { CreditorAccountAdditionalIdentification = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.GenericIdentification>(global::Lyra.Core.EnableBanking.Models.GenericIdentification.CreateFromDiscriminatorValue)?.AsList(); } },
                { "creditor_agent", n => { CreditorAgent = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>(global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification.CreateFromDiscriminatorValue); } },
                { "debtor", n => { Debtor = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>(global::Lyra.Core.EnableBanking.Models.PartyIdentification.CreateFromDiscriminatorValue); } },
                { "debtor_account", n => { DebtorAccount = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AccountIdentification>(global::Lyra.Core.EnableBanking.Models.AccountIdentification.CreateFromDiscriminatorValue); } },
                { "debtor_account_additional_identification", n => { DebtorAccountAdditionalIdentification = n.GetCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.GenericIdentification>(global::Lyra.Core.EnableBanking.Models.GenericIdentification.CreateFromDiscriminatorValue)?.AsList(); } },
                { "debtor_agent", n => { DebtorAgent = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>(global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification.CreateFromDiscriminatorValue); } },
                { "entry_reference", n => { EntryReference = n.GetStringValue(); } },
                { "exchange_rate", n => { ExchangeRate = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.ExchangeRate>(global::Lyra.Core.EnableBanking.Models.ExchangeRate.CreateFromDiscriminatorValue); } },
                { "merchant_category_code", n => { MerchantCategoryCode = n.GetStringValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "reference_number", n => { ReferenceNumber = n.GetStringValue(); } },
                { "reference_number_schema", n => { ReferenceNumberSchema = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.ReferenceNumberScheme>(); } },
                { "remittance_information", n => { RemittanceInformation = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Lyra.Core.EnableBanking.Models.TransactionStatus>(); } },
                { "transaction_amount", n => { TransactionAmount = n.GetObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>(global::Lyra.Core.EnableBanking.Models.AmountType.CreateFromDiscriminatorValue); } },
                { "transaction_date", n => { TransactionDate = n.GetDateValue(); } },
                { "transaction_id", n => { TransactionId = n.GetStringValue(); } },
                { "value_date", n => { ValueDate = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>("balance_after_transaction", BalanceAfterTransaction);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.BankTransactionCode>("bank_transaction_code", BankTransactionCode);
            writer.WriteDateValue("booking_date", BookingDate);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.CreditDebitIndicator>("credit_debit_indicator", CreditDebitIndicator);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>("creditor", Creditor);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AccountIdentification>("creditor_account", CreditorAccount);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.GenericIdentification>("creditor_account_additional_identification", CreditorAccountAdditionalIdentification);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>("creditor_agent", CreditorAgent);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.PartyIdentification>("debtor", Debtor);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AccountIdentification>("debtor_account", DebtorAccount);
            writer.WriteCollectionOfObjectValues<global::Lyra.Core.EnableBanking.Models.GenericIdentification>("debtor_account_additional_identification", DebtorAccountAdditionalIdentification);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.FinancialInstitutionIdentification>("debtor_agent", DebtorAgent);
            writer.WriteStringValue("entry_reference", EntryReference);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.ExchangeRate>("exchange_rate", ExchangeRate);
            writer.WriteStringValue("merchant_category_code", MerchantCategoryCode);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("reference_number", ReferenceNumber);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.ReferenceNumberScheme>("reference_number_schema", ReferenceNumberSchema);
            writer.WriteCollectionOfPrimitiveValues<string>("remittance_information", RemittanceInformation);
            writer.WriteEnumValue<global::Lyra.Core.EnableBanking.Models.TransactionStatus>("status", Status);
            writer.WriteObjectValue<global::Lyra.Core.EnableBanking.Models.AmountType>("transaction_amount", TransactionAmount);
            writer.WriteDateValue("transaction_date", TransactionDate);
            writer.WriteStringValue("transaction_id", TransactionId);
            writer.WriteDateValue("value_date", ValueDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
