// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Lyra.Core.EnableBanking.Models
{
    /// <summary>Specifies the usage of the account</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Usage
    {
        [EnumMember(Value = "PRIV")]
        #pragma warning disable CS1591
        PRIV,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGA")]
        #pragma warning disable CS1591
        ORGA,
        #pragma warning restore CS1591
    }
}
